### ISSUE TITLE
Use redis as meta engine stress test

### ISSUE THREAD

**Issue by tangyoupeng** [juicedata/juicefs#1196]
When redis memory has nothing left, those logs are print.
```
2021/12/23 15:23:38.567529 juicefs[25228] <ERROR>: error: EXECABORT Transaction discarded because of previous errors.
github.com/juicedata/juicefs/pkg/meta.errno({0x7fce4cca5d60, 0xc008b27f90})
	/root/code/juicefs/pkg/meta/utils.go:75 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).txn(0xc000502500, {0x7fce4cd080f8, 0xc008d1a870}, 0xc008b1ab98, {0xc00143fac8, 0x2, 0x2})
	/root/code/juicefs/pkg/meta/redis.go:636 +0x325
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).doMknod(0xc000502500, {0x7fce4cd080f8, 0xc008d1a870}, 0xc00878d470, {0xc00878d491, 0xa}, 0x1, 0x1a4, 0x0, 0x0, ...)
	/root/code/juicefs/pkg/meta/redis.go:935 +0x40b
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Create(0xc000502500, {0x7fce4cd080f8, 0xc008d1a870}, 0x9a0e8, {0xc00878d491, 0xa}, 0xa0a0, 0x8b3, 0x80, 0xc008b1ab70, ...)
	/root/code/juicefs/pkg/meta/base.go:463 +0x1d7
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Create(0xc0001aa5a0, {0x7fce4cd080f8, 0xc008d1a870}, {0xc00878d470, 0x2b}, 0x1a4)
	/root/code/juicefs/pkg/fs/fs.go:774 +0x4c3
	/root/code/juicefs/sdk/java/libjfs/main.go:601 +0x91
```

Delete some files is also failed
```
2021/12/23 16:59:45.397100 juicefs[10601] <ERROR>: error: EXECABORT Transaction discarded because of previous errors.
goroutine 163 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x7fcf48355d60, 0xc0006ffff0})
	/root/code/juicefs/pkg/meta/utils.go:75 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).txn(0xc000582500, {0x7fcf483b80f8, 0xc00026e0c0}, 0xc009a1fe97, {0xc0004cfb68, 0x3, 0x3})
	/root/code/juicefs/pkg/meta/redis.go:636 +0x325
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).doUnlink(0xc000582500, {0x7fcf483b80f8, 0xc00026e0c0}, 0x9a27c, {0xc009a1fe50, 0x10100c000e92480})
	/root/code/juicefs/pkg/meta/redis.go:1040 +0x6f0
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Unlink(0xc000582500, {0x7fcf483b80f8, 0xc00026e0c0}, 0x9a27c, {0xc009a1fe50, 0xa})
	/root/code/juicefs/pkg/meta/base.go:532 +0x19c
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x7fcf483ce808, 0xc000582500}, {0x7fcf483b80f8, 0xc00026e0c0}, 0x9a27c, 0xc0002a8600)
	/root/code/juicefs/pkg/meta/utils.go:232 +0x446
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x7fcf483ce808, 0xc000582500}, {0x7fcf483b80f8, 0xc00026e0c0}, 0x0, {0x7fcf490db0f8, 0x1}, 0x0, 0x0)
	/root/code/juicefs/pkg/meta/utils.go:242 +0x5c
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x7fcf483ce808, 0xc000582500}, {0x7fcf483b80f8, 0xc00026e0c0}, 0x9a271, 0xc0002a8600)
	/root/code/juicefs/pkg/meta/utils.go:227 +0x3f2
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x7fcf483ce808, 0xc000582500}, {0x7fcf483b80f8, 0xc00026e0c0}, 0x0, {0x7fcf490db100, 0x1}, 0x0, 0x0)
	/root/code/juicefs/pkg/meta/utils.go:242 +0x5c
github.com/juicedata/juicefs/pkg/meta.emptyDir.func1(0x0, {0x7fcf490db100, 0x0})
	/root/code/juicefs/pkg/meta/utils.go:220 +0x9e
created by github.com/juicedata/juicefs/pkg/meta.emptyDir
	/root/code/juicefs/pkg/meta/utils.go:218 +0x396
```

Is there a way to allow user to delete some files to free redis memory use

**Comment by davies** [comment]
The deletion of files can't free the memory immediately. We should provide read-only access in case of OOM in redis.
