### ISSUE TITLE
I/O Error when redis bandwidth is 100mbps

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs#1230]
**What happened**:
When redis bandwidth is 100mbps, I/O Error got in vdbench

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**
redis network bandwidth:
```
                        1.91Mb                  3.81Mb                  5.72Mb                  7.63Mb             9.54Mb
└───────────────────────┴───────────────────────┴───────────────────────┴───────────────────────┴────────────────────────
192.168.189.190                                => 192.168.188.164                                 1.62Kb  1.45Kb  1.66Kb
                                               <=                                                 2.42Kb  2.19Kb  2.57Kb
```

vdbench log:
```
09:06:23.527 localhost-0: 09:06:23.527 09:06:23.527 op: write  lun: /data/vdb.1_1.dir/vdb_f0090.file lba:        94208 0x00017000 xfer:     4096 errno: EIO: 'I/O error'
09:06:23.538 localhost-0: 09:06:23.538 09:06:23.538 op: write  lun: /data/vdb.1_1.dir/vdb_f0236.file lba:       159744 0x00027000 xfer:     4096 errno: EIO: 'I/O error'
09:06:24.040
09:06:24.040 'data_errors=50' requested. Abort rd=rd1 after last error.
09:06:24.040
java.lang.RuntimeException: 'data_errors=50' requested. Abort rd=rd1 after last error.
	at Vdb.common.failure(common.java:335)
	at Vdb.common.failure(common.java:284)
	at Vdb.ErrorLog.countErrorsOnMaster(ErrorLog.java:213)
	at Vdb.SlaveOnMaster.processSlave(SlaveOnMaster.java:204)
	at Vdb.SlaveOnMaster.run(SlaveOnMaster.java:42)
```

juicefs log:
```
2021/12/28 09:03:34.290292 juicefs[7] <ERROR>: error: redis: Conn is in a bad state: read tcp 192.168.188.158:43884->10.110.1.49:6379: read: connection reset by peer
goroutine 2549579 [running]:
runtime/debug.Stack(0xc003bc5030, 0x2ccaf90, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/juicedata/juicefs/pkg/meta.errno(0x31ef840, 0xc002196460, 0x4943d00)
	/workspace/juicefs/pkg/meta/utils.go:75 +0xce
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).txn(0xc000502500, 0x3260b18, 0x4943da0, 0xc0006b3e28, 0xc0006b3e18, 0x1, 0x1, 0x0)
	/workspace/juicefs/pkg/meta/redis.go:636 +0x336
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).Write(0xc000502500, 0x3260b18, 0x4943da0, 0x8d4ee, 0x1a00000000000, 0x6797f985, 0x1000, 0xc000001000, 0x0)
	/workspace/juicefs/pkg/meta/redis.go:1690 +0x294
github.com/juicedata/juicefs/pkg/vfs.(*chunkWriter).commitThread(0xc004188420)
	/workspace/juicefs/pkg/vfs/writer.go:200 +0x4f7
created by github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).writeChunk
	/workspace/juicefs/pkg/vfs/writer.go:269 +0x316

2021/12/28 09:03:34.290334 juicefs[7] <WARNING>: write inode:578798 error: input/output error
2021/12/28 09:03:34.290342 juicefs[7] <ERROR>: write inode:578798 indx:0  input/output error
2021/12/28 09:06:10.308262 juicefs[7] <ERROR>: error: redis: connection pool timeout
goroutine 2549752 [running]:
runtime/debug.Stack(0x2d1d8d7, 0x2ccaf90, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/juicedata/juicefs/pkg/meta.errno(0x31e9dc0, 0xc00012a160, 0xc004340c40)
	/workspace/juicefs/pkg/meta/utils.go:75 +0xce
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).doGetAttr(0xc000502500, 0x7fa74805a298, 0xc004340c40, 0x1, 0xc0017ca050, 0x92c5b7)
	/workspace/juicefs/pkg/meta/redis.go:564 +0x14a
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1(0x943f4b, 0xc0016e84e0)
	/workspace/juicefs/pkg/meta/base.go:402 +0x66
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1(0xc00400c080, 0xc0003508e0, 0xc000349c00)
	/workspace/juicefs/pkg/utils/utils.go:126 +0x27
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/workspace/juicefs/pkg/utils/utils.go:125 +0xbd
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0-dev (2021-12-23 0d85c1e9)
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained): 
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
There are a variety of reasons that Redis server may reset the connection, such as bad encryption or incorrect configuration. We'd better leave it for now, and see if there is any other report complaining about this.

**Comment by SandyXSD** [comment]
Current configurations of Redis Client:
ReadTimeout: 30s (default is 3s)
PoolTimeout: 30+1 = 31s
PoolSize: 10 * NumCPU()
