### ISSUE TITLE
I/O Error when minio io depay 1s

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs#1250]
**What happened**:
When minio IO delay 1s, I/O Error will happen

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**
vdbench config:
```
    fsd=fsd1,anchor=/data,depth=1,width=1,files=300,size=640k
    fwd=default,xfersize=4k,fileio=random,fileselect=random,threads=4
    fwd=fwd1,fsd=fsd1,rdpct=20
    rd=rd1,fwd=fwd*,fwdrate=max,format=yes,elapsed=36000000,interval=1
```

Juicefs log:
```
2022/01/04 09:59:37.196589 juicefs[7] <WARNING>: upload chunks/1757/1757471/1757471743_0_4096: timeout after 1m0s (try 4)
2022/01/04 09:59:37.196602 juicefs[7] <WARNING>: upload chunks/1757/1757471/1757471744_0_4096: timeout after 1m0s (try 4)
2022/01/04 09:59:37.196611 juicefs[7] <WARNING>: upload chunks/1757/1757471/1757471745_0_4096: timeout after 1m0s (try 4)
2022/01/04 09:59:37.199735 juicefs[7] <WARNING>: upload chunks/1757/1757471/1757471746_0_4096: timeout after 1m0s (try 4)
2022/01/04 10:00:23.245840 juicefs[7] <ERROR>: flush 580362 timeout after waited 5m0s
2022/01/04 10:00:23.245895 juicefs[7] <ERROR>: pending slice 580362-0: {id:1757471743 chunk:0xc001895d40 off:249856 length:4096 soff:0 slen:4096 writer:0xc0028a9ce0 freezed:true done:false err:0 notify:0xc0025b65a0 started:{wall:13865778697032916162 ext:167994753340 loc:0x494c220} lastMod:{wall:13865778697032921522 ext:167994758702 loc:0x494c220}}
2022/01/04 10:00:23.248028 juicefs[7] <WARNING>: All goroutines (82):
goroutine 240344 [running]:
github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).flush(0xc0028c8140, 0x7f4b186ba2f8, 0xc003039d40, 0xc00068a000, 0x0)
	/workspace/juicefs/pkg/vfs/writer.go:372 +0x5f2
github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).Flush(...)
	/workspace/juicefs/pkg/vfs/writer.go:389
github.com/juicedata/juicefs/pkg/vfs.(*dataWriter).Flush(0xc0001b2960, 0x7f4b186ba2f8, 0xc003039d40, 0x8db0a, 0xc003039d40)
	/workspace/juicefs/pkg/vfs/writer.go:502 +0x65
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Read(0xc00068a090, 0x32628b0, 0xc003039d40, 0x8db0a, 0xc002410000, 0x1000, 0x1000, 0x9d000, 0x1f8, 0x0, ...)
	/workspace/juicefs/pkg/vfs/vfs.go:535 +0x23d
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Read(0xc0007586c0, 0xc002a54360, 0xc000858cd8, 0xc002410000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/workspace/juicefs/pkg/fuse/fuse.go:247 +0xf0
github.com/hanwen/go-fuse/v2/fuse.doRead(0xc000155a20, 0xc000858b40)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/opcode.go:373 +0x9f
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000155a20, 0xc000858b40, 0xc000000000)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:483 +0x2f0
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000155a20, 0xc002aee601)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:456 +0x198
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:323 +0x411
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It is confirmed that the test was not run as expect. MinIO hung forever instead of delayed by 1s. In this case, returning EIO is expected since objects are not uploaded after 5mins.
