### ISSUE TITLE
libjfs.so.gz load bug

### ISSUE THREAD

**Issue by tangyoupeng** [juicedata/juicefs#1459]
**What happened**:
JuiceFS jar contains a binary named as libjfs.so.gz. When load it use java classloader, if theres is also other version JuiceFS jar, may load incorrect file.
cause
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40)
	at com.juicefs.JuiceFileSystemImpl$Libjfs$jnr$ffi$0.jfs_jni_init(Unknown Source)
	at com.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:411)
	at org.apache.hadoop.fs.FilterFileSystem.initialize(FilterFileSystem.java:93)
	at com.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:241)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2816)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:98)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2853)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2835)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:387)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)
	at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)
	at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:102)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:315)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:372)
```

**Comment by tangyoupeng** [comment]
fix by #1458
