### ISSUE TITLE
[MySQL] Error 1264: Out of range value for column 'nlink' at row 1

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#1572]
```
2022/03/14 09:55:18.175861 juicefs[187516] <WARNING>: delete from trash 2022-03-11-13/645609-645610-2: input/output error [base.go:929]
2022/03/14 09:55:18.201480 juicefs[187516] <ERROR>: error: Error 1264: Out of range value for column 'nlink' at row 1
goroutine 44355598 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x2df8860, 0xc005ce7ab8})
        /go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:76 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doRmdir(0xc0000e0c40, {0x2e8fb48, 0x47cf880}, 0x7fffffff10000015, {0xc0040f1940, 0xf})
        /go/src/github.com/juicedata/juicefs/pkg/meta/sql.go:1265 +0x145
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).doCleanupTrash(0xc0000e0c40, 0x0)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:922 +0x63c
created by github.com/juicedata/juicefs/pkg/meta.(*baseMeta).cleanupTrash
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:883 +0x1d4
 [utils.go:76]
```

**Environment**:
- juicefs version 1.0.0-beta2+2022-03-04T03:00:41Z.9e26080
- Ubuntu 20.04
- MariaDB 10.4

**Comment by SandyXSD** [comment]
It's caused when we set nlink to max uint32 (4294967295), which overflows the INT type of MySQL.
