### ISSUE TITLE
Error when a Galera cluster node goes down

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#1946]
**What happened**:

While syncing files to a JuiceFS mount, wand a Galera cluster (3 nodes, connected trough Maxscale in R/W mode) node was shut down, i got:

`Failed to Mkdir: mkdir /jfs/versions: input/output error`

And on `jfs.log` (please note the `WSREP has not yet prepared node for application use`):

```
<ERROR>: error: Error 1180: Got error 6 "No such device or address" during COMMIT
goroutine 72137648 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x2fc5b20, 0xc003cb2360})
        /opt/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc0008cd500, {0x7fd144c07758, 0xc000bb5e00}, 0x5f6fb, {0xc003953ec0, 0xe}, 0x2, 0x1fd, 0x2, 0x0, ...)
        /opt/juicefs/pkg/meta/sql.go:1082 +0x29e
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc0008cd500, {0x7fd144c07758, 0xc000bb5e00}, 0x5f6fb, {0xc003953ec0, 0xe}, 0x0?, 0x1fb?, 0xc0?, 0x0, ...)
        /opt/juicefs/pkg/meta/base.go:619 +0x27e
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0x7fd16f264f18?, {0x7fd144c07758?, 0xc000bb5e00?}, 0xc003953ec0?, {0xc003953ec0?, 0xc003d19320?}, 0x3d80?, 0x19b?, 0xc0?, 0xc003953eb8, ...)
        /opt/juicefs/pkg/meta/base.go:637 +0x5e
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Mkdir(0xc0016aa0a0, {0x2ff2bd8?, 0xc000bb5e00}, 0x5f6fb, {0xc003953ec0, 0xe}, 0x1fd, 0x3d1?)
        /opt/juicefs/pkg/vfs/vfs.go:187 +0x230
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Mkdir(0xc0016b2840, 0xc001e52101?, 0xc0038e63d8, {0xc003953ec0, 0xe}, 0x24a3d60?)
        /opt/juicefs/pkg/fuse/fuse.go:127 +0xcd
github.com/hanwen/go-fuse/v2/fuse.doMkdir(0xc0038e6240?, 0xc0038e6240)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/opcode.go:353 +0x6b
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0016e0000, 0xc0038e6240)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0016e0000, 0x70?)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:456 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:323 +0x52b [utils.go:92]
2022/05/02 19:18:44.993757 juicefs[1379807] <WARNING>: update stats: Error 1047: WSREP has not yet prepared node for application use [sql.go:635]
[mysql] 2022/05/02 19:18:45 packets.go:123: closing bad idle connection: EOF
2022/05/02 19:18:45.997461 juicefs[1379807] <WARNING>: update stats: Error 1927: Failed to reuse connection: #08S01: WSREP has not yet prepared node for application use (nbg1) [sql.go:635]
2022/05/02 19:18:46.006450 juicefs[1379807] <ERROR>: error: Error 1047: WSREP has not yet prepared node for application use
goroutine 72210718 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x2fc5b20, 0xc003cb32c0})
        /opt/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doGetAttr(0xc0008cd500, {0xc0008cd500?, 0x29f3402?}, 0x1, 0xc003d1b0c0?)
        /opt/juicefs/pkg/meta/sql.go:669 +0xd2
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1()
        /opt/juicefs/pkg/meta/base.go:562 +0x46
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
        /opt/juicefs/pkg/utils/utils.go:70 +0x2f
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
        /opt/juicefs/pkg/utils/utils.go:69 +0xdf [utils.go:92]
[mysql] 2022/05/02 19:18:47 packets.go:123: closing bad idle connection: EOF
[mysql] 2022/05/02 19:18:47 connection.go:173: driver: bad connection
2022/05/02 19:18:48.497400 juicefs[1379807] <ERROR>: error: Error 1927: Lost connection to backend server: connection closed by peer (nbg1: Generated event)
goroutine 72137702 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x2fc5b20, 0xc003e06f30})
        /opt/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doLookup(0xc0008cd500, {0xf?, 0x1e?}, 0x1, {0xc003d4cf65, 0x5}, 0xc003d4cf70, 0xc003caa280)
        /opt/juicefs/pkg/meta/sql.go:651 +0x268
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Lookup(0xc0008cd500, {0x7fd144c07758, 0xc001e27c00}, 0x1, {0xc003d4cf65, 0x5}, 0xc003d4cf70, 0xc003caa280)
        /opt/juicefs/pkg/meta/base.go:427 +0x479
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Lookup(0xc0016aa0a0, {0x2ff2bd8?, 0xc001e27c00}, 0x1, {0xc003d4cf65, 0x5})
        /opt/juicefs/pkg/vfs/vfs.go:87 +0x20b
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Lookup(0xc0016b2840, 0xc0021b2101?, 0xc00394e3d8, {0xc003d4cf65, 0x5}, 0x24a3d60?)
        /opt/juicefs/pkg/fuse/fuse.go:69 +0xb8
github.com/hanwen/go-fuse/v2/fuse.doLookup(0xc00394e240?, 0xc00394e240)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/opcode.go:341 +0x6b
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0016e0000, 0xc00394e240)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0016e0000, 0x40?)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:456 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:323 +0x52b [utils.go:92]
[mysql] 2022/05/02 19:18:49 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2022/05/02 19:18:49 connection.go:173: driver: bad connection
[mysql] 2022/05/02 19:18:49 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2022/05/02 19:18:49 connection.go:173: driver: bad connection
[mysql] 2022/05/02 19:18:49 packets.go:37: read tcp 127.0.0.1:44076->127.0.0.1:3306: read: connection reset by peer
[mysql] 2022/05/02 19:18:56 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2022/05/02 19:18:56 connection.go:173: driver: bad connection
[mysql] 2022/05/02 19:18:56 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2022/05/02 19:18:56 connection.go:173: driver: bad connection
[mysql] 2022/05/02 19:19:00 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2022/05/02 19:19:00 packets.go:123: closing bad idle connection: unexpected read from socket
[mysql] 2022/05/02 19:19:01 packets.go:37: unexpected EOF
2022/05/02 19:19:01.044390 juicefs[1379807] <ERROR>: error: invalid connection
goroutine 72211246 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x2fc5000, 0xc0002975f0})
        /opt/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc0008cd500, {0x7fd144c07758, 0xc001ac80c0}, 0x6e8d1, {0x430ada0, 0x1}, 0x2, 0x1fd, 0x2, 0x0, ...)
        /opt/juicefs/pkg/meta/sql.go:1082 +0x29e
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc0008cd500, {0x7fd144c07758, 0xc001ac80c0}, 0x6e8d1, {0x430ada0, 0x1}, 0x0?, 0x1b8?, 0xc0?, 0x0, ...)
        /opt/juicefs/pkg/meta/base.go:619 +0x27e
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0x7fd144c54430?, {0x7fd144c07758?, 0xc001ac80c0?}, 0x10?, {0x430ada0?, 0xc001fa7a70?}, 0x0?, 0x0?, 0x0?, 0xc001e206f8, ...)
        /opt/juicefs/pkg/meta/base.go:637 +0x5e
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Mkdir(0xc0016aa0a0, {0x2ff2bd8?, 0xc001ac80c0}, 0x6e8d1, {0x430ada0, 0x1}, 0x1fd, 0x1fa?)
        /opt/juicefs/pkg/vfs/vfs.go:187 +0x230
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Mkdir(0xc0016b2840, 0xc002e5a101?, 0xc00304b158, {0x430ada0, 0x1}, 0x24a3d60?)
        /opt/juicefs/pkg/fuse/fuse.go:127 +0xcd
github.com/hanwen/go-fuse/v2/fuse.doMkdir(0xc00304afc0?, 0xc00304afc0)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/opcode.go:353 +0x6b
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0016e0000, 0xc00304afc0)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0016e0000, 0xa0?)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:456 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:323 +0x52b [utils.go:92]
```

**Environment**:
- JuiceFS version: juicefs version 1.0.0-dev+2022-04-29.99f2fc3e
- Metadata engine: MariaDB (Galera Cluster)

**Comment by davies** [comment]
When a node is down, is it expected that the cluster is still available?

The error is expected when the meta service is down.
