### ISSUE TITLE
rename may fail under high concurrent workload

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#1956]
**What happened**:
```
2022/05/06 10:49:22.665429 juicefs[792051] <WARNING>: Already tried 50 times, returning: write conflict { start_ts:433010864490283422 conflict_
ts:433010864503390219 key:"jfs\375A\312\000\000\000\000\000\000\000I"  } [tkv.go:611]
2022/05/06 10:49:22.666016 juicefs[792051] <ERROR>: error: write conflict { start_ts:433010864490283422 conflict_ts:433010864503390219 key:"jfs\375A\312\000\000\000\000\000\000\000I"  }
goroutine 68096 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x2df7ea0, 0xc007b07790})
        /root/go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:76 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).doRename(0xc001f7a1c0, {0x2e8cda8, 0xc0006dd920}, 0xca, {0xc0076ae33a, 0x24}, 0x2be898ec, {0xc0
025a384a, 0xc}, 0x0, ...)
        /root/go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:1370 +0x449
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Rename(0xc001f7a1c0, {0x2e8cda8, 0xc0006dd920}, 0xca, {0xc0076ae33a, 0xc0006dd920}, 0x2be898e
c, {0xc0025a384a, 0xc000d7da40}, 0x0, ...)
        /root/go/src/github.com/juicedata/juicefs/pkg/meta/base.go:703 +0x311
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Rename(0xc0019265a0, {0x2e8cda8, 0xc0006dd920}, {0xc0076ae330, 0x2e}, {0xc0025a3770, 0xe6}, 0
x0)
        /root/go/src/github.com/juicedata/juicefs/pkg/fs/fs.go:466 +0x595
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).putObject(0xc0006e5060, {0x2e46778, 0xc0062d6510}, {0xc003d9f805, 0xc25b07}, {0xc0025a37
70, 0xe6}, _, {{0x0, 0x0}, ...})
        /root/go/src/github.com/juicedata/juicefs/pkg/gateway/gateway.go:626 +0x54f
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).PutObject(_, {_, _}, {_, _}, {_, _}, _, {{0x0, 0x0}, ...})
        /root/go/src/github.com/juicedata/juicefs/pkg/gateway/gateway.go:652 +0x38e
github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler({0x29a1c40, 0x29a1c30}, {0x2e172f0, 0xc0033ea1e0}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/object-handlers.go:1621 +0x2031
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2047
github.com/minio/minio/cmd.httpTraceHdrs.func1({0x2e172f0, 0xc0033ea1e0}, 0x203000)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/handler-utils.go:371 +0x53
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2047
github.com/minio/minio/cmd.maxClients.func1({0x2e172f0, 0xc0033ea1e0}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/handler-api.go:148 +0x38a
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2047
github.com/minio/minio/cmd.collectAPIStats.func1({0x2e172f0, 0xc0033ea140}, 0x0)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/handler-utils.go:386 +0x112
net/http.HandlerFunc.ServeHTTP(0xc002012e00, {0x2e172f0, 0xc0033ea140}, 0xa0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setRedirectHandler.func1({0x2e172f0, 0xc0033ea140}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:145 +0x1d1
net/http.HandlerFunc.ServeHTTP(0x2e172c0, {0x2e172f0, 0xc0033ea140}, 0x10)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.addCustomHeaders.func1({0x2e172c0, 0xc005e93680}, 0xc0037ebce0)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:660 +0x136
net/http.HandlerFunc.ServeHTTP(0x26b4aa0, {0x2e172c0, 0xc005e93680}, 0x17)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.addSecurityHeaders.func1({0x2e172c0, 0xc005e93680}, 0x0)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:669 +0x184
net/http.HandlerFunc.ServeHTTP(0x0, {0x2e172c0, 0xc005e93680}, 0x0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setBucketForwardingHandler.func1({0x2e172c0, 0xc005e93680}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:543 +0x237
net/http.HandlerFunc.ServeHTTP(0xc003d9f804, {0x2e172c0, 0xc005e93680}, 0x2275784)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setRequestValidityHandler.func1({0x2e172c0, 0xc005e93680}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:531 +0x394
net/http.HandlerFunc.ServeHTTP(0x7f8fc8378078, {0x2e172c0, 0xc005e93680}, 0x7f8ff8624498)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setHTTPStatsHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:465 +0x127
net/http.HandlerFunc.ServeHTTP(0x43c4830, {0x2e1e8e0, 0xc00066b260}, 0x0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:49 +0x102
net/http.HandlerFunc.ServeHTTP(0x30, {0x2e1e8e0, 0xc00066b260}, 0x10000c002ba0de8)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:68 +0x1a5
net/http.HandlerFunc.ServeHTTP(0x26b4aa0, {0x2e1e8e0, 0xc00066b260}, 0xc9)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP({{0x2dfc960, 0xc005e93590}}, {0x2e1e8e0, 0xc00066b260}, 0x6)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/crossdomain-xml-handler.go:51 +0xef
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:161 +0xb0
net/http.HandlerFunc.ServeHTTP(0x0, {0x2e1e8e0, 0xc00066b260}, 0x10)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setReservedBucketHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:293 +0x2c2
net/http.HandlerFunc.ServeHTTP(0x28d1d2c, {0x2e1e8e0, 0xc00066b260}, 0x0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:262 +0x303
net/http.HandlerFunc.ServeHTTP(0x0, {0x2e1e8e0, 0xc00066b260}, 0x30bcf161)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setTimeValidityHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:357 +0x3a3
net/http.HandlerFunc.ServeHTTP(0xc002012e00, {0x2e1e8e0, 0xc00066b260}, 0x4)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setIgnoreResourcesHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:452 +0x337
net/http.HandlerFunc.ServeHTTP(0xc002012e00, {0x2e1e8e0, 0xc00066b260}, 0x0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setAuthHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/auth-handler.go:495 +0x2e4
net/http.HandlerFunc.ServeHTTP(0x27d1800, {0x2e1e8e0, 0xc00066b260}, 0x39)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setSSETLSHandler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:703 +0x3ca
net/http.HandlerFunc.ServeHTTP(0xc0024db400, {0x2e1e8e0, 0xc00066b260}, 0x7f8fc83ecd58)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.filterReservedMetadata.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012e00)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:108 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc002012d00, {0x2e1e8e0, 0xc00066b260}, 0x1)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001b37680, {0x2e1e8e0, 0xc00066b260}, 0xc002012c00)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x2e1e8e0, 0xc00066b260}, 0xc002012c00)
        /root/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x49dd140, {0x2e1e8e0, 0xc00066b260}, 0xb)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP({{0x2dfc960, 0xc001c95880}}, {0x2e1e8e0, 0xc00066b260}, 0x2df97c0)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/generic-handlers.go:688 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1({0x2e1e8e0, 0xc00066b260}, 0xc0042c3ee0)
        /root/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/http/server.go:101 +0x1d5
net/http.HandlerFunc.ServeHTTP(0x0, {0x2e1e8e0, 0xc00066b260}, 0x49a5d8)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.serverHandler.ServeHTTP({0x2e0fc38}, {0x2e1e8e0, 0xc00066b260}, 0xc002012c00)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0033ea0a0, {0x2e46778, 0xc00016fce0})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8
 [utils.go:76]
```

**What you expected to happen**:

The upload through S3 gateway should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

upload file to S3 gateway with high (500+) concurrent clients.

**Comment by davies** [comment]
When we add or remove files, we update the mtime and ctime of the parent directory. Maybe we can reduce the accuracy of mtime/ctime to reduce the conflict on updating the attributes.
