### ISSUE TITLE
database is locked with sqlite.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2068]
**What happened**:
https://github.com/juicedata/juicefs/runs/6520018979?check_suite_focus=true
when start 3 juicefs sync process to upload files with juicefs gateway, it will report the following error:

```
2022/05/20 06:28:31.584449 juicefs[6994] <ERROR>: error: database is locked
goroutine 935 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3012e00, 0xc006b95f40})
	/home/runner/work/juicefs/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doGetAttr(0xc000be4000, {0xc0023a61d8, 0x0}, 0x1, 0x1)
	/home/runner/work/juicefs/juicefs/pkg/meta/sql.go:672 +0xd2
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1()
	/home/runner/work/juicefs/juicefs/pkg/meta/base.go:574 +0x46
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
	/home/runner/work/juicefs/juicefs/pkg/utils/utils.go:70 +0x2f
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/home/runner/work/juicefs/juicefs/pkg/utils/utils.go:69 +0xe5 [utils.go:92]
2022/05/20 06:28:36.867346 juicefs[6994] <ERROR>: error: not inserted or updated
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:465 +0x127
net/http.HandlerFunc.ServeHTTP(0x451fe70, {0x3036c30, 0xc00207db20}, 0x0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:49 +0x102
net/http.HandlerFunc.ServeHTTP(0xc0018313c0, {0x3036c30, 0xc00207db20}, 0x5ef9bd)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:68 +0x1a5
net/http.HandlerFunc.ServeHTTP(0x281c240, {0x3036c30, 0xc00207db20}, 0x2c)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP({{0x3014aa0, 0xc00180f8f0}}, {0x3036c30, 0xc00207db20}, 0x6)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/crossdomain-xml-handler.go:51 +0xef
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:161 +0xb0
net/http.HandlerFunc.ServeHTTP(0x0, {0x3036c30, 0xc00207db20}, 0x10)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setReservedBucketHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:293 +0x2c2
net/http.HandlerFunc.ServeHTTP(0x2a6df8b, {0x3036c30, 0xc00207db20}, 0x0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:262 +0x303
net/http.HandlerFunc.ServeHTTP(0x0, {0x3036c30, 0xc00207db20}, 0x295f5abb)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setTimeValidityHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:357 +0x3a3
net/http.HandlerFunc.ServeHTTP(0xc0025d1800, {0x3036c30, 0xc00207db20}, 0x1)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setIgnoreResourcesHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:[452](https://github.com/juicedata/juicefs/runs/6520018979?check_suite_focus=true#step:4:465) +0x337
net/http.HandlerFunc.ServeHTTP(0xc0025d1800, {0x3036c30, 0xc00207db20}, 0x0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setAuthHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/auth-handler.go:495 +0x2e4
net/http.HandlerFunc.ServeHTTP(0x29501c0, {0x3036c30, 0xc00207db20}, 0x39)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.setSSETLSHandler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:703 +0x3ca
net/http.HandlerFunc.ServeHTTP(0xc00297dc00, {0x3036c30, 0xc00207db20}, 0x7f16912fbff0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.filterReservedMetadata.func1({0x3036c30, 0xc00207db20}, 0xc0025d1800)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:108 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc0025d1700, {0x3036c30, 0xc00207db20}, 0xc000b51501)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000b4e600, {0x3036c30, 0xc00207db20}, 0xc0025d1200)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x3036c30, 0xc00207db20}, 0xc0025d1200)
	/home/runner/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x4b3ed20, {0x3036c30, 0xc00207db20}, 0x7f16bd36e108)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP({{0x3014aa0, 0xc0017af7e0}}, {0x3036c30, 0xc00207db20}, 0x3011720)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/generic-handlers.go:688 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1({0x3036c30, 0xc00207db20}, 0x10000c001a49af0)
	/home/runner/go/pkg/mod/github.com/juicedata/minio@v0.0.0-20220324072921-2057662dce6d/cmd/http/server.go:101 +0x1d5
net/http.HandlerFunc.ServeHTTP(0xc002a10b57, {0x3036c30, 0xc00207db20}, 0x47a86e)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
net/http.serverHandler.ServeHTTP({0xc001e08660}, {0x3036c30, 0xc00207db20}, 0xc0025d1200)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc001bf9900, {0x305db10, 0xc000bac2a0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:3034 +0x4e8 [utils.go:92]
2022/05/20 06:28:36.867416 juicefs[6994] <WARNING>: set object data/file1 on upload 185c750b-44cd-4ad8-a10e-a23c23f07f1b: input/output error [gateway.go:694]
```

**What you expected to happen**:
database should not be locked

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
May be duplicated with #1439
