### ISSUE TITLE
Statement is timeout when use oceanbase as meta engine.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2115]
**What happened**:
https://github.com/juicedata/juicefs/runs/6619573475?check_suite_focus=true
```
2022/05/27 10:46:11.769364 juicefs[1125156] <INFO>: Syncing from file:///root/actions-runner/_work/juicefs/juicefs/data/ to s3://myjfs/data/ [sync.go:619]
2022/05/27 10:46:11.772530 juicefs[1125157] <INFO>: Syncing from file:///root/actions-runner/_work/juicefs/juicefs/data/ to s3://myjfs/data/ [sync.go:619]
2022/05/27 10:46:11.777670 juicefs[1125158] <INFO>: Syncing from file:///root/actions-runner/_work/juicefs/juicefs/data/ to s3://myjfs/data/ [sync.go:619]
2022/05/27 10:46:33.681259 juicefs[1125124] <ERROR>: error: Error 4012: Statement is timeout
goroutine 865 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x306bd20, 0xc002dd9158})
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doUnlink(0xc00007af00, {0x3098b98, 0xc0018c3d40}, 0x1e, {0xc002dd75f0, 0x2})
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/sql.go:1320 +0x21e
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Unlink(0xc00007af00, {0x3098b98, 0xc0018c3d40}, 0x1e, {0xc002dd75f0, 0x2})
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/base.go:714 +0x1b8
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x30a5e70, 0xc00007af00}, {0x3098b98?, 0xc0018c3d40}, 0x1e, 0xc0019ab080)
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/utils.go:256 +0x45c
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x30a5e70, 0xc00007af00}, {0x3098b98, 0xc0018c3d40}, 0xc0077fcdce?, {0xc0077fcdce, 0x24}, 0xc00214fef0?, 0xc0077fcdc0?)
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/utils.go:266 +0x5c
github.com/juicedata/juicefs/pkg/meta.Remove({0x30a5e70, 0xc00007af00}, {0x3098b98, 0xc0018c3d40}, 0xd?, {0xc0077fcdce, 0x24})
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/utils.go:289 +0x174
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Rmr(0xc0007fc660, {0x3098b98?, 0xc0018c3d40}, {0xc0077fcdc0, 0x32})
	/root/actions-runner/_work/juicefs/juicefs/pkg/fs/fs.go:441 +0x2aa
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).CompleteMultipartUpload(_, {_, _}, {_, _}, {_, _}, {_, _}, {0xc000281400, ...}, ...)
	/root/actions-runner/_work/juicefs/juicefs/pkg/gateway/gateway.go:892 +0x792
github.com/minio/minio/cmd.objectAPIHandlers.CompleteMultipartUploadHandler({0x2b76860?, 0x2b76850?}, {0x30801d8?, 0xc007e95040}, 0xc007012500)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
This is a problem of oceanbase.
