### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by FourSpaces** [juicedata/juicefs#2132]
**What happened**:
按照教程在JuiceFS Java 客户端部署完成后，运行 spark-sql --master yarn  出现错误：

```
[hadoop@10 /data/juicefs/juicefs-1.0.0-beta3/sdk/java/target]$ spark-sql --master yarn
22/05/28 15:18:54 WARN HiveConf: HiveConf of name hive.metastore.db.encoding does not exist
22/05/28 15:18:54 WARN HiveConf: HiveConf of name hive.hwi.listen.host does not exist
22/05/28 15:18:54 WARN HiveConf: HiveConf of name hive.hwi.listen.port does not exist
2022/05/28 15:18:54.529039 juicefs[682382] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
22/05/28 15:18:55 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
22/05/28 15:19:03 ERROR YarnClientSchedulerBackend: The YARN application has already ended! It might have been killed or the Application Master may have failed to start. Check the YARN application logs for more details.
22/05/28 15:19:03 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: Application application_1653663390536_0007 failed 2 times due to AM Container for appattempt_1653663390536_0007_000002 exited with  exitCode: -1000
Failing this attempt.Diagnostics: [2022-05-28 15:19:02.915]java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
        at io.juicefs.JuiceFileSystemImpl$FileInputStream.<init>(JuiceFileSystemImpl.java:719)
        at io.juicefs.JuiceFileSystemImpl.open(JuiceFileSystemImpl.java:940)
        at org.apache.hadoop.fs.FilterFileSystem.open(FilterFileSystem.java:164)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:906)
        at org.apache.hadoop.yarn.util.FSDownload.unpack(FSDownload.java:331)
        at org.apache.hadoop.yarn.util.FSDownload.downloadAndUnpack(FSDownload.java:307)
        at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:287)
        at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:68)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:418)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:415)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:415)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:246)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:239)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:227)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

For more detailed output, check the application tracking page: http://10.68.0.7:5004/cluster/app/application_1653663390536_0007 Then click on links to logs of each attempt.
. Failing the application.
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:95)
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:201)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:562)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2589)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:934)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:928)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:49)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>(SparkSQLCLIDriver.scala:321)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:155)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
22/05/28 15:19:03 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
22/05/28 15:19:03 WARN MetricsSystem: Stopping a MetricsSystem that is not running
Exception in thread "main" org.apache.spark.SparkException: Application application_1653663390536_0007 failed 2 times due to AM Container for appattempt_1653663390536_0007_000002 exited with  exitCode: -1000
Failing this attempt.Diagnostics: [2022-05-28 15:19:02.915]java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
        at io.juicefs.JuiceFileSystemImpl$FileInputStream.<init>(JuiceFileSystemImpl.java:719)
        at io.juicefs.JuiceFileSystemImpl.open(JuiceFileSystemImpl.java:940)
        at org.apache.hadoop.fs.FilterFileSystem.open(FilterFileSystem.java:164)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:906)
        at org.apache.hadoop.yarn.util.FSDownload.unpack(FSDownload.java:331)
        at org.apache.hadoop.yarn.util.FSDownload.downloadAndUnpack(FSDownload.java:307)
        at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:287)
        at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:68)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:418)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:415)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:415)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:246)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:239)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:227)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

For more detailed output, check the application tracking page: http://10.68.0.7:5004/cluster/app/application_1653663390536_0007 Then click on links to logs of each attempt.
. Failing the application.
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:95)
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:201)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:562)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2589)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:934)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:928)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:49)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>(SparkSQLCLIDriver.scala:321)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:155)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**What you expected to happen**:
正常在yarn 上运行 spark-sql。可以在juicefs上创建表。

**How to reproduce it (as minimally and precisely as possible)**:
不知道在别的环境上如何重现。

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
   version 1.0.0-beta2+2022-03-04T03:00:41Z.9e26080

- Cloud provider or hardware configuration running JuiceFS:
   腾讯云：EMR-V3.3.0
   部署组件：	
   [hdfs-3.2.2, yarn-3.2.2,   zookeeper-3.6.1,  openldap-2.4.44,
     knox-1.2.0, hive-3.1.2, spark-3.0.2, kyuubi-1.4.1, ranger-2.1.0]
   java版本：openjdk version "1.8.0_282"
   Master：4核16G 200G云盘   x  2
   Core：16核心32G 400G云盘 x  3
   
- OS (e.g `cat /etc/os-release`):
      NAME="Tencent Linux"
      VERSION="2.4"
      ID="tlinux"
      ID_LIKE="rhel fedora centos"
      VERSION_ID="2.4"
      PRETTY_NAME="Tencent Linux 2.4"
      ANSI_COLOR="0;31"
      CPE_NAME="cpe:/o:tlinux:linux:2"
      HOME_URL="https://tlinux.qq.com/"

- Kernel (e.g. `uname -a`):
      Linux 10.68.0.13 5.4.119-19-0007 #1 SMP Mon Jul 12 17:46:17 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

- Object storage (cloud provider and region, or self maintained):
       腾讯云COS
- Metadata engine info (version, cloud provider managed or self maintained):
       腾讯云redis 5.0
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
       内网
- Others:

**Comment by tangyoupeng** [comment]
The juicefs-hadoop-1.0.0-beta2.jar was packaged with jdk11. You can use  [juicefs-hadoop-1.0.0-beta3-amd64.jar](https://github.com/juicedata/juicefs/releases/download/v1.0.0-beta3/juicefs-hadoop-1.0.0-beta3-amd64.jar) which was build with jdk8 or build by yourself
