### ISSUE TITLE
input/output error on meta engine sqlite3

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#2681]
**What happened**:

Meta URL is:
`juicefs mount "sqlite3:///db/juicefs.db?_journal_mode=WAL&_busy_timeout=5000&_synchronous=NORMAL" /mnt/jfs`

```
<ERROR>: error: database is locked
goroutine 20813108 [running]:
runtime/debug.Stack()
#011/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/juicedata/juicefs/pkg/meta.errno({0x2fc86c0, 0x4002632bc0})
#011/usr/local/src/juicefs/pkg/meta/utils.go:104 +0x108
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0x40001d2c00, {0x304b768, 0x4000768000}, 0xc90d1, {0x4003abb590, 0x16}, 0x1, 0x180, 0x0, 0x0, ...)
#011/usr/local/src/juicefs/pkg/meta/sql.go:1210 +0x2e0
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0x4000266a00, {0x304b768, 0x4000768000}, 0xc90d1, {0x4003abb590, 0x16}, 0x1, 0x180, 0x0, 0x0, ...)
#011/usr/local/src/juicefs/pkg/meta/base.go:707 +0x234
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Create(0x4000266a00, {0x304b768, 0x4000768000}, 0xc90d1, {0x4003abb590, 0x16}, 0x180, 0x0, 0x200c2, 0x4001f79e90, ...)
#011/usr/local/src/juicefs/pkg/meta/base.go:714 +0x9c
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Create(0x4000dd2160, {0x304be28, 0x4000768000}, 0xc90d1, {0x4003abb590, 0x16}, 0x8180, 0x0, 0x200c2)
#011/usr/local/src/juicefs/pkg/vfs/vfs.go:362 +0x1a8
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Create(0x40005640c0, 0x40054b82a0, 0x4002e8b398, {0x4003abb590, 0x16}, 0x4002e8b308)
#011/usr/local/src/juicefs/pkg/fuse/fuse.go:229 +0xb4
github.com/hanwen/go-fuse/v2/fuse.doCreate(0x4001043a20, 0x4002e8b200)
#011/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220822092405-ece777deb343/fuse/opcode.go:163 +0x90
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0x4001043a20, 0x4002e8b200)
#011/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220822092405-ece777deb343/fuse/server.go:483 +0x214
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0x4001043a20, 0x1)
#011/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220822092405-ece777deb343/fuse/server.go:456 +0xbc
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
#011/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220822092405-ece777deb343/fuse/server.go:323 +0x5e4 [utils.go:104]
2022/09/06 21:50:53.792559 juicefs[1826845] <INFO>: slow operation: create (823505,.gtkbuilder.its.922Rmi,-rw-------:0100600): input/output error [fh:0] <40.486606> [accesslog.go:65]
<ERROR>: update session: database is locked [sql.go:1932]
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  `juicefs version 1.1.0-dev+2022-08-26.bb841274`
- Cloud provider or hardware configuration running JuiceFS: `ARM64 with 80 Cores, 256Gb RAM`
- OS (e.g `cat /etc/os-release`): `Ubuntu 22.04.1 LTS`
- Kernel (e.g. `uname -a`): `5.15.0-46-generic aarch64`
- Metadata engine info (version, cloud provider managed or self maintained): `sqlite3 3.37.2`

**Comment by solracsf** [comment]
Adding this thread that may help here: https://github.com/mattn/go-sqlite3/issues/274

**Comment by solracsf** [comment]
On our side we're just `rsync`ing from a NFS volume to JuiceFS mount: 
`rsync -arv /data 10.10.10.1:/srv/juicefs`

There is an average of 400K files of different sizes on it.

**Comment by solracsf** [comment]
On the sender side:

```
rsync: [receiver] close failed on "/srv/juicefs/slprj/sldrt_win64/_sharedutils/.shared_file.dmr.tvezGA": Input/output error (5)
rsync error: error in file IO (code 11) at receiver.c(871) [receiver=3.2.3]
rsync: [sender] write error: Broken pipe (32)
```

**Comment by Hexilee** [comment]
> Adding this thread that may help here: [mattn/go-sqlite3#274](https://github.com/mattn/go-sqlite3/issues/274)

According to the upstream issue, write operation of sqlite3 will lock the whole database file. So, set `MaxOpenConns` to 1 here https://github.com/juicedata/juicefs/blob/main/pkg/meta/sql.go#L222 should fix this issue, but it may reduce TPS of meta engine significantly in readonly cases.
