### ISSUE TITLE
I run a mapreduce examples pi job, but get a NullPointerException in JuiceFileSystemImpl

### ISSUE THREAD

**Issue by himcc** [juicedata/juicefs#2690]
**What happened**:
I run a mapreduce examples pi job, but get a NullPointerException in JuiceFileSystemImpl.
[hdp@hh1 ~]$ hadoop jar ${HADOOP_HOME}/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.3.4.jar pi 10 100
Number of Maps  = 10
Samples per Map = 100
2022-09-07 19:05:56,639 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 0 minutes that is used for deletion instead
2022-09-07 19:05:56,640 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 0 minutes, Emptier interval = 0 minutes.
java.lang.NullPointerException
        at io.juicefs.JuiceFileSystemImpl.error(JuiceFileSystemImpl.java:192)
        at io.juicefs.JuiceFileSystemImpl.mkdirs(JuiceFileSystemImpl.java:1444)
        at io.juicefs.JuiceFileSystemImpl.mkdirs(JuiceFileSystemImpl.java:1441)
        at io.juicefs.JuiceFileSystemImpl.mkdirs(JuiceFileSystemImpl.java:1441)
        at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2388)
        at org.apache.hadoop.fs.FilterFileSystem.mkdirs(FilterFileSystem.java:341)
        at org.apache.hadoop.examples.QuasiMonteCarlo.estimatePi(QuasiMonteCarlo.java:283)
        at org.apache.hadoop.examples.QuasiMonteCarlo.run(QuasiMonteCarlo.java:360)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
        at org.apache.hadoop.examples.QuasiMonteCarlo.main(QuasiMonteCarlo.java:368)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:236)

**What you expected to happen**:
get value of pi

**How to reproduce it (as minimally and precisely as possible)**:
hadoop jar ${HADOOP_HOME}/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.3.4.jar pi 10 100

**Anything else we need to know?**
job concat a temporary path like "QuasiMonteCarlo_1662546514068_436928233/in",and then mkdir.
https://github.com/apache/hadoop/blob/rel/release-3.3.4/hadoop-mapreduce-project/hadoop-mapreduce-examples/src/main/java/org/apache/hadoop/examples/QuasiMonteCarlo.java#L283

And, it will make dir recursively in JuiceFileSystemImpl.  https://github.com/juicedata/juicefs/blob/v1.0.0/sdk/java/src/main/java/io/juicefs/JuiceFileSystemImpl.java#L1441
The temporary path is a relative path. getParent recursively , will get a empty string。And the, mkdir fail, go to line 1444, f.getParent() will get null.Then, go to line 192 , p.toString() will  throw a NullPointerException.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:v1.0.0
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by tangyoupeng** [comment]
Can you provide the accesslog for this issue?
If you did not enable accesslog. You should add juicefs.access-log=/tmp/juicefs.access.log in core-site.xml  first and re-run the pi application.

**Comment by tangyoupeng** [comment]
#2696
