### ISSUE TITLE
error: pq: column "id" does not exist

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2760]
**What happened**:

```
chengdeMacBook-Pro:scripts chengzhou$ cat test_gc.sh 
export PGPASSWORD=postgres
printf "\set AUTOCOMMIT on\ndrop database if exists test1; create database test1; " |  psql -U postgres -h localhost
mc rb myminio/test-bucket --force
export JFS_RSA_PASSPHRASE=12345678
set -e 
./juicefs-1.0.0-beta1 format postgres://postgres:postgres@127.0.0.1:5432/test2?sslmode=disable test-volume --block-size 40959 --compress lz4 --shards 1 --storage minio --capacity 1017 --inodes 823776628 --trash-days 1614 --force --no-update --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
./juicefs-1.1.0-dev gc postgres://postgres:postgres@127.0.0.1:5432/test2?sslmode=disable --delete --threads 83 --debug

```

```
chengdeMacBook-Pro:scripts chengzhou$ ./test_gc.sh 
NOTICE:  database "test2" does not exist, skipping
DROP DATABASE
CREATE DATABASE
mc: <ERROR> Unable to validate target `myminio/test-bucket`. Bucket `test-bucket` does not exist.
2022/09/15 15:22:13.395610 juicefs[61130] <INFO>: Meta address: postgres://postgres@127.0.0.1:5432/test2?sslmode=disable
[xorm] [info]  2022/09/15 15:22:13.395866 PING DATABASE postgres
2022/09/15 15:22:13.418340 juicefs[61130] <WARNING>: The latency to database is too high: 22.49465ms
2022/09/15 15:22:13.421726 juicefs[61130] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket
2022/09/15 15:22:13.421856 juicefs[61130] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/
2022/09/15 15:22:13.656583 juicefs[61130] <INFO>: Volume is formatted as {Name:test-volume UUID:98da1e73-68ce-482d-acdf-d332dd62a452 Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:16384 Compression:lz4 Shards:1 Partitions:0 Capacity:1091995435008 Inodes:823776628 EncryptKey: TrashDays:1614}
2022/09/15 15:22:13.720610 juicefs[61131] <INFO>: Meta address: postgres://postgres:****@127.0.0.1:5432/test2?sslmode=disable [interface.go:411]
[xorm] [info]  2022/09/15 15:22:13.720941 PING DATABASE postgres
2022/09/15 15:22:13.733695 juicefs[61131] <WARNING>: The latency to database is too high: 12.767796ms [sql.go:216]
2022/09/15 15:22:13.745098 juicefs[61131] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/15 15:22:13.745308 juicefs[61131] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [gc.go:108]
2022/09/15 15:22:13.752630 juicefs[61131] <ERROR>: error: pq: column "id" does not exist
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x6d9b760, 0xc0001be120})
	/Users/chengzhou/Documents/juicefs/pkg/meta/utils.go:104 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).ListSlices(0xc0005c50c0, {0x2800?, 0xc0001ac720?}, 0xc0005e5e30, 0x0?, 0xc0002ee130)
	/Users/chengzhou/Documents/juicefs/pkg/meta/sql.go:2578 +0xec
github.com/juicedata/juicefs/cmd.gc(0xc0005c6980)
	/Users/chengzhou/Documents/juicefs/cmd/gc.go:179 +0xbd3
github.com/urfave/cli/v2.(*Command).Run(0xc0005f0360, 0xc0005c6780)
	/Users/chengzhou/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc0006836c0, {0x6db3430?, 0xc00019e008}, {0xc0008a8080, 0x7, 0x8})
	/Users/chengzhou/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/chengzhou/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
github.com/juicedata/juicefs/cmd.Main({0xc0001fa070?, 0x7?, 0x7?})
	/Users/chengzhou/Documents/juicefs/cmd/main.go:86 +0x250c
main.main()
	/Users/chengzhou/Documents/juicefs/main.go:29 +0x2e [utils.go:104]
2022/09/15 15:22:13.752697 juicefs[61131] <FATAL>: list all slices: input/output error [gc.go:181]

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
duplicated with #2717
