### ISSUE TITLE
juicefs 1.0  unknown cause panic 

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#2953]
```
panic: runtime error: index out of range [-7276294671082564993]

goroutine 78399554 [running]:
path/filepath.(*lazybuf).append(...)
        /usr/local/go/src/path/filepath/path.go:50
path/filepath.Clean({0xc0286ec660, 0x4b})
        /usr/local/go/src/path/filepath/path.go:111 +0xb0e
path/filepath.Dir({0xc0286ec660, 0xc0286ec660})
        /usr/local/go/src/path/filepath/path.go:586 +0x4a
github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).flushPage(0xc000a87b20, {0xc0286ec660, 0x5c}, {0xc041d78000, 0x400000, 0x400000})
        /go/src/github.com/juicedata/juicefs/pkg/chunk/disk_cache.go:179 +0x16a
github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).stage(0xc000a87b20, {0xc01a77e020, 0x1f}, {0xc041d78000, 0x400000, 0x400000}, 0x1)
        /go/src/github.com/juicedata/juicefs/pkg/chunk/disk_cache.go:331 +0x11e
github.com/juicedata/juicefs/pkg/chunk.(*cacheManager).stage(0xc0014107e0, {0xc01a77e020, 0x1f}, {0xc041d78000, 0x400000, 0x400000}, 0x80)
        /go/src/github.com/juicedata/juicefs/pkg/chunk/disk_cache.go:740 +0x8d
github.com/juicedata/juicefs/pkg/chunk.(*wSlice).upload.func1()
        /go/src/github.com/juicedata/juicefs/pkg/chunk/cached_store.go:428 +0x133
created by github.com/juicedata/juicefs/pkg/chunk.(*wSlice).upload
        /go/src/github.com/juicedata/juicefs/pkg/chunk/cached_store.go:411 +0x18f
```

**Comment by davies** [comment]
Maybe this is caused by memory error, can't reproduce it.
