### ISSUE TITLE
List of unstable tests that have been skipped

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#3105]
1. fsck
2. gc
3. warmup
4. info

**Comment by SandyXSD** [comment]
These 4 tests are not stable and may hang like forever for unknown reason, so we disable them temporarily by #3103 .

**Comment by SandyXSD** [comment]
Go stacks:
```
2023-03-29T09:16:01.4676690Z goroutine 0 [idle]:
2023-03-29T09:16:01.4677113Z runtime.futex()
2023-03-29T09:16:01.4677654Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/sys_linux_amd64.s:559 +0x21 fp=0x7fffeec853e0 sp=0x7fffeec853d8 pc=0x481cc1
2023-03-29T09:16:01.4828390Z runtime.futexsleep(0x4ff?, 0x53862a0?, 0xc000068500?)
2023-03-29T09:16:01.4829461Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/os_linux.go:69 +0x36 fp=0x7fffeec85430 sp=0x7fffeec853e0 pc=0x446d96
2023-03-29T09:16:01.4829902Z runtime.notesleep(0x53863e8)
2023-03-29T09:16:01.4830346Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/lock_futex.go:160 +0x87 fp=0x7fffeec85468 sp=0x7fffeec85430 pc=0x41ed67
2023-03-29T09:16:01.4831060Z runtime.mPark()
2023-03-29T09:16:01.4831607Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/proc.go:1457 +0x25 fp=0x7fffeec85488 sp=0x7fffeec85468 pc=0x450305
2023-03-29T09:16:01.4832133Z runtime.stoplockedm()
2023-03-29T09:16:01.4832552Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/proc.go:2448 +0x65 fp=0x7fffeec854d8 sp=0x7fffeec85488 pc=0x451f05
2023-03-29T09:16:01.4834439Z runtime.schedule()
2023-03-29T09:16:01.4835064Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/proc.go:3193 +0x3d fp=0x7fffeec85510 sp=0x7fffeec854d8 pc=0x453bdd
2023-03-29T09:16:01.4835554Z runtime.park_m(0xc000e384e0?)
2023-03-29T09:16:01.4847128Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/proc.go:3363 +0x14d fp=0x7fffeec85540 sp=0x7fffeec85510 pc=0x45418d
2023-03-29T09:16:01.4847493Z runtime.mcall()
2023-03-29T09:16:01.4847886Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/asm_amd64.s:448 +0x43 fp=0x7fffeec85550 sp=0x7fffeec85540 pc=0x47db83
```
and
```
2023-03-29T09:16:01.5127318Z goroutine 59 [syscall, 8 minutes]:
2023-03-29T09:16:01.5127594Z runtime.notetsleepg(0x454965?, 0x0?)
2023-03-29T09:16:01.5128017Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/lock_futex.go:236 +0x34 fp=0xc000e267a0 sp=0xc000e26768 pc=0x41f074
2023-03-29T09:16:01.5128355Z os/signal.signal_recv()
2023-03-29T09:16:01.5128758Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/sigqueue.go:152 +0x2f fp=0xc000e267c0 sp=0xc000e267a0 pc=0x47bc2f
2023-03-29T09:16:01.5129080Z os/signal.loop()
2023-03-29T09:16:01.5129463Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/os/signal/signal_unix.go:23 +0x19 fp=0xc000e267e0 sp=0xc000e267c0 pc=0x5a70b9
2023-03-29T09:16:01.5129784Z runtime.goexit()
2023-03-29T09:16:01.5130155Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000e267e8 sp=0xc000e267e0 pc=0x47fdc1
2023-03-29T09:16:01.5130503Z created by os/signal.Notify.func1.1
2023-03-29T09:16:01.5130862Z 	/opt/hostedtoolcache/go/1.19.7/x64/src/os/signal/signal.go:151 +0x2a
```
