### ISSUE TITLE
TestMySQLClient randomly fails because of imcompacted slices

### ISSUE THREAD

**Issue by Hexilee** [juicedata/juicefs#3265]
Repeated execute `TestMySQLClient`, you may get test failed:

```bash
> go clean -testcache && go test -timeout 30s -run '^TestMySQLClient$' github.com/juicedata/juicefs/pkg/meta
2023/02/24 15:42:01.992999 juicefs[328842] <ERROR>: error: Error 1146: Table 'dev.jfs_node' doesn't exist
goroutine 53 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x1a3dc00, 0xc0007aa498})
	/home/hexi/src/juicefs/pkg/meta/utils.go:105 +0xad
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doGetAttr(0x0?, {0x0?, 0x0?}, 0x0?, 0x0?)
	/home/hexi/src/juicefs/pkg/meta/sql.go:806 +0x4a
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1()
	/home/hexi/src/juicefs/pkg/meta/base.go:715 +0x49
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
	/home/hexi/src/juicefs/pkg/utils/utils.go:76 +0x32
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/home/hexi/src/juicefs/pkg/utils/utils.go:75 +0xdf [utils.go:105]
2023/02/24 15:42:02.400584 juicefs[328842] <INFO>: Create session 1 OK with version: 1.1.0-dev+unknown [base.go:311]
2023/02/24 15:42:02.401024 juicefs[328842] <INFO>: get session: meta.Session{Sid:0x1, Expire:time.Date(2023, time.February, 24, 15, 43, 2, 0, time.Local), SessionInfo:meta.SessionInfo{Version:"1.1.0-dev+unknown", HostName:"ArchLinux", MountPoint:"", ProcessID:328842}, Sustained:[]meta.Ino(nil), Flocks:[]meta.Flock(nil), Plocks:[]meta.Plock(nil)} [sql.go:478]
2023/02/24 15:42:02.636820 juicefs[328842] <INFO>: close session 1: %!s(<nil>) [base.go:410]
2023/02/24 15:42:02.853273 juicefs[328842] <WARNING>: File name is too long as a trash entry, truncating it: fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff -> 1-20-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff [base.go:1382]
2023/02/24 15:42:02.872863 juicefs[328842] <INFO>: cleanup trash: deleted 6 files in 16.906372ms [base.go:1418]
2023/02/24 15:42:16.569269 juicefs[328842] <INFO>: chunk 4135:1 was changed 72 -> 24 [sql.go:2462]
2023/02/24 15:42:16.569824 juicefs[328842] <INFO>: compacted chunk 1118 was not used [sql.go:2505]
2023/02/24 15:42:16.569857 juicefs[328842] <INFO>: compaction for 4135:1 is wasted, delete slice 1118 (67108864 bytes) [sql.go:2512]
--- FAIL: TestMySQLClient (14.69s)
    base_test.go:992: expect 1 slice, but got [{Id:1114 Size:67108864 Off:0 Len:31457280} {Id:1115 Size:8 Off:0 Len:8} {Id:1114 Size:67108864 Off:31457288 Len:10485752} {Id:1116 Size:8 Off:0 Len:8} {Id:1114 Size:67108864 Off:41943048 Len:25165816}]
FAIL
FAIL	github.com/juicedata/juicefs/pkg/meta	14.707s
FAIL
```

**Comment by davies** [comment]
should be fixed by #3592
