### ISSUE TITLE
hadoop cli error but use is normal

### ISSUE THREAD

**Issue by kpretty** [juicedata/juicefs#3331]
**What happened**:
use hadoop cli `hadoop fs -ls jfs://juices/` error but data can be obtained normally
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/77819741/224909837-06b21faa-d97a-46c2-bc9d-cc9ba244066f.png">

**What you expected to happen**:
```shell
2023-03-14 14:00:12,701 WARN juicefs.JuiceFileSystemImpl: read root failed
java.io.FileNotFoundException: File root does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:666)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:987)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:656)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at io.juicefs.JuiceFileSystemImpl.readFile(JuiceFileSystemImpl.java:409)
	at io.juicefs.JuiceFileSystemImpl.updateUidAndGrouping(JuiceFileSystemImpl.java:432)
	at io.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:379)
	at io.juicefs.JuiceFileSystem.lambda$startTrashEmptier$1(JuiceFileSystem.java:87)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at io.juicefs.JuiceFileSystem.startTrashEmptier(JuiceFileSystem.java:85)
	at io.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:73)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:352)
	at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:250)
	at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:233)
	at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:104)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:177)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  1.0.3+2022-12-27.e4bf15a
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): macos m1
- Kernel (e.g. `uname -a`): Darwin Kernel Version 22.3.0
- Object storage (cloud provider and region, or self maintained): minio self maintained
- Metadata engine info (version, cloud provider managed or self maintained): redis 7.0.8
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by tangyoupeng** [comment]
Did you configured juicefs.users or juicefs.groups?

**Comment by kpretty** [comment]
@tangyoupeng Yeah

**Comment by tangyoupeng** [comment]
Maybe the configured fie are missing?

**Comment by kpretty** [comment]
@tangyoupeng maybe！！！I added it in an existing hadoop environment, and it is normal when I try to use a new hadoop environment
