### ISSUE TITLE
Deadlock error when create file or mkdir

### ISSUE THREAD

**Issue by zml1206** [juicedata/juicefs#3665]
```
2023/05/23 14:00:42.142442 juicefs[2755] <ERROR>: error: Error 1213: Deadlock found when trying to get lock; try restarting transaction
goroutine 587180074 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x32858a0, 0xc003e3da88})
        /go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:104 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc00082c720, {0x32b6140, 0xc000b99440}, 0x325091, {0xc0042ce400, 0x1c}, 0x1, 0x1a4, 0x0, 0x0, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/sql.go:1206 +0x2da
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc0009a0000, {0x32b6140, 0xc000b99440}, 0x325091, {0xc0042ce400, 0x1c}, 0xe8?, 0x309?, 0xc0?, 0x0, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:743 +0x2a8
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Create(0xc0009a0000, {0x32b6140?, 0xc000b99440?}, 0x20?, {0xc0042ce400?, 0xc0042ce400?}, 0x0?, 0x0?, 0x8241, 0xc004baffd8, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:750 +0x109
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Create(0xc00199c000, {0x32b6ea0?, 0xc000b99440}, 0x325091, {0xc0042ce400, 0x1c}, 0x81a4, 0x728?, 0xc0?)
        /go/src/github.com/juicedata/juicefs/pkg/vfs/vfs.go:362 +0x256
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Create(0xc000bfa400, 0xc0037ae101?, 0xc003b98198, {0xc0042ce400, 0x1c}, 0xc003b98108)
        /go/src/github.com/juicedata/juicefs/pkg/fuse/fuse.go:229 +0xd5
github.com/hanwen/go-fuse/v2/fuse.doCreate(0xc003b98000?, 0xc003b98000)
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20221212033224-ed3172586347/fuse/opcode.go:164 +0x66
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000bf2160, 0xc003b98000)
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20221212033224-ed3172586347/fuse/server.go:492 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000bf2160, 0x0?)
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20221212033224-ed3172586347/fuse/server.go:465 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20221212033224-ed3172586347/fuse/server.go:332 +0x53e [utils.go:104]
2023/05/23 14:00:42.142495 juicefs[2755] <INFO>: slow operation: create (3297425,fb95476ee3b5b4de6a4f7b02.tmp,-rw-r--r--:0100644): input/output error [fh:0] <41.398236> [accesslog.go:65]
```

```
2022/06/19 08:30:15.109397 juicefs[20856] <WARNING>: Already tried 50 times, returning: Error 1213: Deadlock found when trying to get lock;try restarting transaction [sql.go:645]
2022/06/19 08:30:15.109774 juicefs[20856] <ERROR>: error: Error 1213: Deadlock found when trying to get lock; try restarting transactiongoroutine 14449551 [running]:
runtime/debug.Stack()        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x30254c0, 0xc0049f7fc8})        /go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:93 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc0002900d8, {0x7f1774c663c0, 0xc00538a300}, 0x3b3a26, {0xc003afc250, 0xa}, 0x2, 0x1ed, 0x12, 0x0, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/sql.go:1172 +0x2d3github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc0001da500, {0x7f1774c663c0, 0xc00538a300}, 0x3b3a26, {0xc003afc250, 0xa}, 0x50, 0x0, 0x0, 0x0, ...)        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:648 +0x284
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0x0, {0x7f1774c663c0, 0xc00538a300}, 0x282f500, {0xc003afc250, 0x29e5700}, 0xa300, 0x538, 0xc0, 0xc003afc248, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:666 +0x5e
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Mkdir(0xc000143cc0, {0x30bed28, 0xc00538a300}, 0x3b3a26, {0xc003afc250, 0xa}, 0x1ed, 0x3ae)
        /go/src/github.com/juicedata/juicefs/pkg/vfs/vfs.go:187 +0x23c
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Mkdir(0xc000787620, 0xc0084ae101, 0xc0009de858, {0xc003afc250, 0xa}, 0x2510160)
        /go/src/github.com/juicedata/juicefs/pkg/fuse/fuse.go:127 +0xcd
github.com/hanwen/go-fuse/v2/fuse.doMkdir(0xc0009de6c0, 0xc0009de6c0)
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/opcode.go:353 +0x6b
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000585600, 0xc0009de6c0)
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000585600, 0xc0)
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:456 +0x110
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:323 +0x534 [utils.go:93]
2022/06/19 08:30:15.109863 juicefs[20856] <INFO>: slow operation: mkdir (3881510,_temporary,?rwxr-xr-x:00755): input/output error <40.905207> [accesslog.go:65]
```

**What happened**:
Occasional deadlock error when create file or mkdir
**What you expected to happen**:
Should not deadlock
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version: 1.0.4+2023-04-06.f1c475d
- metadata engine: mysql
- mysql isolation level: REPEATABLE-READ

**Comment by davies** [comment]
Can you provide a way to reproduce this?

**Comment by zml1206** [comment]
Sorry, I have no way to reproduce, this happens every few hours in our environment.
I can describe how we use it, the underlying storage is minio cluster, juiceFs is used as a cache proxy, and spark is used to read.

**Comment by zml1206** [comment]
> Can you provide a way to reproduce this?

Sorry, I have no way to reproduce, this happens every few hours in our environment.
I can describe how we use it, the underlying storage is minio cluster, juiceFs is used as a cache proxy, and spark is used to read.

**Comment by davies** [comment]
What's the version MySQL?

**Comment by davies** [comment]
@zml1206 Can you try #3677 , or pick it on to release-1.0 branch?

**Comment by zml1206** [comment]
> 



> What's the version MySQL?

mysql  Ver 14.14 Distrib 5.7.36, for Linux (x86_64) using  EditLine wrapper

**Comment by zml1206** [comment]
Test passed，thanks @davies
