### ISSUE TITLE
juiceFs 整合 hadoop 使用异常

### ISSUE THREAD

**Issue by chenxu8989** [juicedata/juicefs#3681]
**What happened**:

执行命令 hadoop fs -ls /

后出现如下异常

```log
2023/05/25 15:44:10.346368 juicefs[25278] <WARNING>: The latency to database is too high: 25.149877ms [sql.go:240]
2023-05-25 15:44:10,348 WARN juicefs.JuiceFileSystemImpl: 2023/05/25 15:44:10.346368 juicefs[25278] <WARNING>: The latency to database is too high: 25.149877ms [sql.go:240]
2023-05-25 15:44:10,565 WARN utils.NodesFetcher: fetch from:http://ds-3:8088/ws/v1/cluster/nodes/ failed, switch to another url
io.juicefs.shaded.org.json.JSONException: JSONObject["node"] not found.
        at io.juicefs.shaded.org.json.JSONObject.get(JSONObject.java:566)
        at io.juicefs.shaded.org.json.JSONObject.getJSONArray(JSONObject.java:760)
        at io.juicefs.utils.YarnNodesFetcher.parseNodes(YarnNodesFetcher.java:60)
        at io.juicefs.utils.NodesFetcher.getNodes(NodesFetcher.java:109)
        at io.juicefs.utils.YarnNodesFetcher.getNodes(YarnNodesFetcher.java:54)
        at io.juicefs.utils.NodesFetcher.fetchNodes(NodesFetcher.java:65)
        at io.juicefs.JuiceFileSystemImpl.discoverNodes(JuiceFileSystemImpl.java:727)
        at io.juicefs.JuiceFileSystemImpl.initCache(JuiceFileSystemImpl.java:690)
        at io.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:412)
        at org.apache.hadoop.fs.FilterFileSystem.initialize(FilterFileSystem.java:98)
        at io.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:71)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:342)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:252)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:235)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:105)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:179)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
2023-05-25 15:44:10,582 WARN utils.NodesFetcher: java.net.ConnectException: 拒绝连接 (Connection refused)
2023-05-25 15:44:10,617 WARN utils.NodesFetcher: fetch from:http://ds-2:8088/ws/v1/cluster/nodes/ failed, switch to another url
io.juicefs.shaded.org.json.JSONException: JSONObject["node"] not found.
        at io.juicefs.shaded.org.json.JSONObject.get(JSONObject.java:566)
        at io.juicefs.shaded.org.json.JSONObject.getJSONArray(JSONObject.java:760)
        at io.juicefs.utils.YarnNodesFetcher.parseNodes(YarnNodesFetcher.java:60)
        at io.juicefs.utils.NodesFetcher.getNodes(NodesFetcher.java:109)
        at io.juicefs.utils.YarnNodesFetcher.getNodes(YarnNodesFetcher.java:54)
        at io.juicefs.utils.NodesFetcher.fetchNodes(NodesFetcher.java:65)
        at io.juicefs.JuiceFileSystemImpl.discoverNodes(JuiceFileSystemImpl.java:727)
        at io.juicefs.JuiceFileSystemImpl.initCache(JuiceFileSystemImpl.java:690)
        at io.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:412)
        at org.apache.hadoop.fs.FilterFileSystem.initialize(FilterFileSystem.java:98)
        at io.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:71)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:342)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:252)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:235)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:105)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:179)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
2023-05-25 15:44:10,684 WARN utils.NodesFetcher: fetch from:http://ds-3:8088/ws/v1/cluster/nodes/ failed, switch to another url
io.juicefs.shaded.org.json.JSONException: JSONObject["node"] not found.
        at io.juicefs.shaded.org.json.JSONObject.get(JSONObject.java:566)
        at io.juicefs.shaded.org.json.JSONObject.getJSONArray(JSONObject.java:760)
        at io.juicefs.utils.YarnNodesFetcher.parseNodes(YarnNodesFetcher.java:60)
        at io.juicefs.utils.NodesFetcher.getNodes(NodesFetcher.java:109)
        at io.juicefs.utils.YarnNodesFetcher.getNodes(YarnNodesFetcher.java:54)
        at io.juicefs.utils.NodesFetcher.fetchNodes(NodesFetcher.java:65)
        at io.juicefs.JuiceFileSystemImpl.discoverNodes(JuiceFileSystemImpl.java:727)
        at io.juicefs.JuiceFileSystemImpl.initCache(JuiceFileSystemImpl.java:690)
        at io.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:412)
        at io.juicefs.JuiceFileSystem.lambda$startTrashEmptier$1(JuiceFileSystem.java:87)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at io.juicefs.JuiceFileSystem.startTrashEmptier(JuiceFileSystem.java:85)
        at io.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:73)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:342)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:252)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:235)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:105)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:179)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
2023-05-25 15:44:10,686 WARN utils.NodesFetcher: java.net.ConnectException: 拒绝连接 (Connection refused)
2023-05-25 15:44:10,704 WARN utils.NodesFetcher: fetch from:http://ds-2:8088/ws/v1/cluster/nodes/ failed, switch to another url
io.juicefs.shaded.org.json.JSONException: JSONObject["node"] not found.
        at io.juicefs.shaded.org.json.JSONObject.get(JSONObject.java:566)
        at io.juicefs.shaded.org.json.JSONObject.getJSONArray(JSONObject.java:760)
        at io.juicefs.utils.YarnNodesFetcher.parseNodes(YarnNodesFetcher.java:60)
        at io.juicefs.utils.NodesFetcher.getNodes(NodesFetcher.java:109)
        at io.juicefs.utils.YarnNodesFetcher.getNodes(YarnNodesFetcher.java:54)
        at io.juicefs.utils.NodesFetcher.fetchNodes(NodesFetcher.java:65)
        at io.juicefs.JuiceFileSystemImpl.discoverNodes(JuiceFileSystemImpl.java:727)
        at io.juicefs.JuiceFileSystemImpl.initCache(JuiceFileSystemImpl.java:690)
        at io.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:412)
        at io.juicefs.JuiceFileSystem.lambda$startTrashEmptier$1(JuiceFileSystem.java:87)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at io.juicefs.JuiceFileSystem.startTrashEmptier(JuiceFileSystem.java:85)
        at io.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:73)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:342)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:252)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:235)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:105)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:179)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
2023-05-25 15:44:10,711 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 0 minutes that is used for deletion instead
2023-05-25 15:44:10,711 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 0 minutes, Emptier interval = 0 minutes.
Found 2 items
drwxrwxrwx   - hdfs supergroup       4096 2023-05-25 14:19 /tmp
drwxr-xr-x   - hdfs supergroup       4096 2023-05-25 14:18 /user
```

juicefs.discover-nodes-url 修改为 jfs://myjfs/etc/nodes 并上传nodes文件后  hadoop fs -ls / 正常, 但执行命令 hadoop fs -mkdir /flink 出现如下异常

```log
2023-05-25 15:48:49,376 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 0 minutes that is used for deletion instead
2023-05-25 15:48:49,376 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 0 minutes, Emptier interval = 0 minutes.
2023/05/25 15:48:49.452862 juicefs[25861] <ERROR>: error: Error 1264 (22003): Out of range value for column 'uid' at row 1
goroutine 17 [running, locked to thread]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x7fcd43210a20, 0xc0020270b0})
        /root/juicefs/pkg/meta/utils.go:122 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc000bd0060, {0x7fcd43248468, 0xc001155980}, 0x1, {0xc002024285, 0x5}, 0x2, 0x1ed, 0x0, 0x0, ...)
        /root/juicefs/pkg/meta/sql.go:1197 +0x2a5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc000220a00, {0x7fcd43248468, 0xc001155980}, 0x1, {0xc002024285, 0x5}, 0x8?, 0x0?, 0x0?, 0x0, ...)
        /root/juicefs/pkg/meta/base.go:1261 +0x2d5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0xc000220a00, {0x7fcd43248468?, 0xc001155980?}, 0x1, {0xc002024285?, 0x0?}, 0x2da0?, 0x4320?, 0xcd?, 0xc0020242a0, ...)
        /root/juicefs/pkg/meta/base.go:1285 +0x78
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Mkdir(0xc000c1e8c0, {0x7fcd43248468?, 0xc001155980}, {0xc002024284, 0x6}, 0x1ed)
        /root/juicefs/pkg/fs/fs.go:432 +0x354
main.jfs_mkdir(0x7fcd3fc41e78?, 0xc000180000?, 0x0?, 0x1ed)
        /root/juicefs/sdk/java/libjfs/main.go:753 +0x86 [utils.go:122]
mkdir: jfs://myjfs/
2023-05-25 15:48:49,454 ERROR juicefs.JuiceFileSystemImpl: 2023/05/25 15:48:49.452862 juicefs[25861] <ERROR>: error: Error 1264 (22003): Out of range value for column 'uid' at row 1
goroutine 17 [running, locked to thread]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x7fcd43210a20, 0xc0020270b0})
        /root/juicefs/pkg/meta/utils.go:122 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc000bd0060, {0x7fcd43248468, 0xc001155980}, 0x1, {0xc002024285, 0x5}, 0x2, 0x1ed, 0x0, 0x0, ...)
        /root/juicefs/pkg/meta/sql.go:1197 +0x2a5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc000220a00, {0x7fcd43248468, 0xc001155980}, 0x1, {0xc002024285, 0x5}, 0x8?, 0x0?, 0x0?, 0x0, ...)
        /root/juicefs/pkg/meta/base.go:1261 +0x2d5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0xc000220a00, {0x7fcd43248468?, 0xc001155980?}, 0x1, {0xc002024285?, 0x0?}, 0x2da0?, 0x4320?, 0xcd?, 0xc0020242a0, ...)
        /root/juicefs/pkg/meta/base.go:1285 +0x78
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Mkdir(0xc000c1e8c0, {0x7fcd43248468?, 0xc001155980}, {0xc002024284, 0x6}, 0x1ed)
        /root/juicefs/pkg/fs/fs.go:432 +0x354
main.jfs_mkdir(0x7fcd3fc41e78?, 0xc000180000?, 0x0?, 0x1ed)
        /root/juicefs/sdk/java/libjfs/main.go:753 +0x86 [utils.go:122]
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 

    自己编译的版本  juicefs-hadoop-1.1-dev.jar

    hadoop : 3.3.3

- Cloud provider or hardware configuration running JuiceFS:

- OS (e.g `cat /etc/os-release`):

    ```shell
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"
    ```

- Kernel (e.g. `uname -a`):

    ```shell
    Linux ds-1 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    ```

- Object storage (cloud provider and region, or self maintained): Minio

- Metadata engine info (version, cloud provider managed or self maintained):

    ```shell
    mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64) using  EditLine wrapper
    ```

- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):

- Others:

    - juiceFs

        ```shell
        juicefs format \
        --storage minio \
        --bucket http://ds-1:9000/cluster \
        --access-key WdKPualu83fzK2L2 \
        --secret-key Sd5uQdJDUi0QJ2zFdQ0ZPlBpBZrOff5S \
        "mysql://root:123456@(ds-1:3306)/juicefs" \
        myjfs
        
        rm -rf /opt/juicefs/cache/*
        rm -rf /data/jfs/*
        
        juicefs mount \
        --background \
        --cache-dir /opt/juicefs/cache \
        --cache-size 512000 \
        "mysql://root:123456@(ds-1:3306)/juicefs" \
        /data/jfs
        
        [root@ds-1 ~]# juicefs bench /data/jfs
          Write big blocks count: 1024 / 1024 [==============================================================]  done
           Read big blocks count: 1024 / 1024 [==============================================================]  done
        Write small blocks count: 100 / 100 [==============================================================]  done
         Read small blocks count: 100 / 100 [==============================================================]  done
          Stat small files count: 100 / 100 [==============================================================]  done
        Benchmark finished!
        BlockSize: 1 MiB, BigFileSize: 1024 MiB, SmallFileSize: 128 KiB, SmallFileCount: 100, NumThreads: 1
        Time used: 33.3 s, CPU: 35.2%, Memory: 458.0 MiB
        +------------------+------------------+---------------+
        |       ITEM       |       VALUE      |      COST     |
        +------------------+------------------+---------------+
        |   Write big file |      60.53 MiB/s |  16.92 s/file |
        |    Read big file |     120.97 MiB/s |   8.46 s/file |
        | Write small file |     25.8 files/s | 38.80 ms/file |
        |  Read small file |    139.0 files/s |  7.19 ms/file |
        |        Stat file |    903.1 files/s |  1.11 ms/file |
        |   FUSE operation | 17841 operations |    1.94 ms/op |
        |      Update meta |  1117 operations |    6.30 ms/op |
        |       Put object |   356 operations |  912.55 ms/op |
        |       Get object |   256 operations |  216.21 ms/op |
        |    Delete object |     0 operations |    0.00 ms/op |
        | Write into cache |   356 operations |    4.06 ms/op |
        |  Read from cache |   100 operations |    3.50 ms/op |
        +------------------+------------------+---------------+
        ```

        

    - core-site.xml

        ```xml
        <?xml version="1.0" encoding="UTF-8"?>
        <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
        <configuration>
            <property>
                <name>fs.defaultFS</name>
                <value>jfs://myjfs</value>
            </property>
            <property>
                <name>hadoop.proxyuser.hive.hosts</name>
                <value>*</value>
            </property>
            <property>
                <name>hadoop.proxyuser.hive.groups</name>
                <value>*</value>
            </property>
            <property>
                <name>hadoop.proxyuser.hive.users</name>
                <value>*</value>
            </property>
            <property>
                <name>hadoop.http.staticuser.user</name>
                <value>admin</value>
            </property>
            <property>
                <name>ha.zookeeper.quorum</name>
                <value>ds-1:2181,ds-2:2181,ds-3:2181</value>
            </property>
            <property>
                <name>hadoop.tmp.dir</name>
                <value>/data/hadoop/tmp</value>
            </property>
            <property>
                <name>fs.jfs.impl</name>
                <value>io.juicefs.JuiceFileSystem</value>
            </property>
            <property>
                <name>fs.AbstractFileSystem.jfs.impl</name>
                <value>io.juicefs.JuiceFS</value>
            </property>
            <property>
                <name>juicefs.meta</name>
                <value>mysql://root:123456@(ds-1:3306)/juicefs</value>
            </property>
            <property>
                <name>juicefs.cache-dir</name>
                <value>/opt/juicefs/cache</value>
            </property>
            <property>
                <name>juicefs.cache-size</name>
                <value>1024</value>
            </property>
            <property>
                <name>juicefs.discover-nodes-url</name>
                <value>yarn</value>
            </property>
            <property>
                <name>juicefs.bucket</name>
                <value>http://ds-1:9000/cluster</value>
            </property>
            <property>
                <name>juicefs.access-log</name>
                <value>/tmp/juicefs.access.log</value>
            </property>
            <property>
                <name>juicefs.cache-full-block</name>
                <value>true</value>
            </property>
            <property>
                <name>juicefs.free-space</name>
                <value>0.1</value>
            </property>
            <property>
                <name>juicefs.open-cache</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.attr-cache</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.entry-cache</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.dir-entry-cache</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.max-uploads</name>
                <value>20</value>
            </property>
            <property>
                <name>juicefs.max-deletes</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.get-timeout</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.put-timeout</name>
                <value>60</value>
            </property>
            <property>
                <name>juicefs.memory-size</name>
                <value>300</value>
            </property>
            <property>
                <name>juicefs.prefetch</name>
                <value>1</value>
            </property>
            <property>
                <name>juicefs.io-retries</name>
                <value>10</value>
            </property>
            <property>
                <name>juicefs.writeback</name>
                <value>true</value>
            </property>
        ```

**Comment by tangyoupeng** [comment]
It was fixed by https://github.com/juicedata/juicefs/pull/3680 yesterday
