### ISSUE TITLE
libgfapi not compatible: juicefs.gluster crash on format

### ISSUE THREAD

**Issue by CodingPoeta** [juicedata/juicefs#4043]
**What happened**:

```
> ./juicefs.gluster format redis://localhost:6379/1 myjfs --storage=gluster --bucket=localhost/gvr3
2023/09/08 23:25:57.332561 juicefs[3085867] <INFO>: Meta address: redis://localhost:6379/1 [interface.go:497]
2023/09/08 23:25:57.418486 juicefs[3085867] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:84]
2023/09/08 23:25:57.445811 juicefs[3085867] <INFO>: Ping redis latency: 443.364µs [redis.go:3572]
2023/09/08 23:25:57.483198 juicefs[3085867] <INFO>: Data use gluster://gvr3/myjfs/ [format.go:471]
SIGSEGV: segmentation violation
PC=0x7fafb0da809f m=8 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x2809040, 0xc000c1eb58)
        /usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc000c1eb30 sp=0xc000c1eaf8 pc=0x40b22b
github.com/juicedata/gogfapi/gfapi._C2func_glfs_readdirplus(0x7faf4c0eeef8, 0xc0000cc5a0)
        _cgo_gotypes.go:592 +0x56 fp=0xc000c1eb58 sp=0xc000c1eb30 pc=0x18038b6
github.com/juicedata/gogfapi/gfapi.(*Fd).Readdir.func1(0x41c2c8?, 0xc000c1ebe0?)
        /home/a/go/pkg/mod/github.com/juicedata/gogfapi@v0.0.0-20230626071140-fc28e5537825/gfapi/fd.go:221 +0x50 fp=0xc000c1eba0 sp=0xc000c1eb58 pc=0x18060f0
github.com/juicedata/gogfapi/gfapi.(*Fd).Readdir(0x4?, 0x0)
        /home/a/go/pkg/mod/github.com/juicedata/gogfapi@v0.0.0-20230626071140-fc28e5537825/gfapi/fd.go:221 +0xc5 fp=0xc000c1ee40 sp=0xc000c1eba0 pc=0x1805ec5
```

**Anything else we need to know?**

If your glusterfs is installed from source, this crash might happen on some version of glusterfs. 

Affected libgfapi 10.4 - 12dev.

**Comment by CodingPoeta** [comment]
With libgfapi-10.2, TestGluster will fail but not crash

**Comment by sgammon** [comment]
@CodingPoeta We ran into something similar, I think:

```
2024/01/21 07:45:14.832351 juicefs[40055] <INFO>: Data use gluster://gv0/jfs/ [format.go:471]
SIGSEGV: segmentation violation
PC=0x7fec1fa61d2e m=14 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x2861d90, 0xc0014c0b20)
	/usr/lib/go-1.21/src/runtime/cgocall.go:157 +0x4b fp=0xc0014c0af8 sp=0xc0014c0ac0 pc=0x40b24b
github.com/juicedata/gogfapi/gfapi._C2func_glfs_readdirplus(0x7feb700b3688, 0xc0000ed290)
	_cgo_gotypes.go:591 +0x56 fp=0xc0014c0b20 sp=0xc0014c0af8 pc=0x1816f96
github.com/juicedata/gogfapi/gfapi.(*Fd).Readdir.func1(0x41c2e8?, 0xc0014c0ba8?)
	/home/sam/go/pkg/mod/github.com/juicedata/gogfapi@v0.0.0-20230626071140-fc28e5537825/gfapi/fd.go:221 +0x50 fp=0xc0014c0b68 sp=0xc0014c0b20 pc=0x18197d0
github.com/juicedata/gogfapi/gfapi.(*Fd).Readdir(0x4?, 0x0)
	/home/sam/go/pkg/mod/github.com/juicedata/gogfapi@v0.0.0-20230626071140-fc28e5537825/gfapi/fd.go:221 +0xc5 fp=0xc0014c0e08 sp=0xc0014c0b68 pc=0x18195a5
github.com/juicedata/gogfapi/gfapi.(*File).Readdir(...)
	/home/sam/go/pkg/mod/github.com/juicedata/gogfapi@v0.0.0-20230626071140-fc28e5537825/gfapi/file.go:100
github.com/juicedata/juicefs/pkg/object.(*gluster).readDirSorted(0x0?, {0xc001c237c8, 0x4}, 0x1)
	/home/sam/src/juicefs/pkg/object/gluster.go:170 +0x114 fp=0xc0014c0f68 sp=0xc0014c0e08 pc=0x1df1514
github.com/juicedata/juicefs/pkg/object.(*gluster).List(0x438b0a?, {0xc001c237c8, 0x4}, {0x0, 0x0}, {0x385d230?, 0x40?}, 0x3b9aca00, 0x2?)
	/home/sam/src/juicefs/pkg/object/gluster.go:222 +0x2eb fp=0xc0014c10c8 sp=0xc0014c0f68 pc=0x1df212b
github.com/juicedata/juicefs/pkg/object.(*withPrefix).List(0xc000deb200, {0x0?, 0x2?}, {0x0?, 0x4142a5?}, {0x385d230, 0x1}, 0x0?, 0xa0?)
	/home/sam/src/juicefs/pkg/object/prefix.go:132 +0x106 fp=0xc0014c1170 sp=0xc0014c10c8 pc=0x1e127e6
github.com/juicedata/juicefs/pkg/object.ListAllWithDelimiter({0x38abf50, 0xc000deb200}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x1)
	/home/sam/src/juicefs/pkg/object/object_storage.go:193 +0x88 fp=0xc0014c1228 sp=0xc0014c1170 pc=0x1e05c28
github.com/juicedata/juicefs/pkg/sync.ListAll({0x38abf50?, 0xc000deb200}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x1)
	/home/sam/src/juicefs/pkg/sync/sync.go:112 +0x914 fp=0xc0014c13c0 sp=0xc0014c1228 pc=0x1e6d274
github.com/juicedata/juicefs/cmd.format(0xc000a09540)
	/home/sam/src/juicefs/cmd/format.go:477 +0x1856 fp=0xc0014c1928 sp=0xc0014c13c0 pc=0x2658c96
github.com/urfave/cli/v2.(*Command).Run(0xc000b9f200, 0xc000a08b00)
	/home/sam/go/pkg/mod/github.com/juicedata/cli/v2@v2.19.4-0.20230605075551-9c9c5c0dce83/command.go:177 +0x6d4 fp=0xc0014c1a28 sp=0xc0014c1928 pc=0x66a394
github.com/urfave/cli/v2.(*App).RunContext(0xc00151c000, {0x3891610?, 0x563c420}, {0xc00091a400, 0x8, 0x8})
	/home/sam/go/pkg/mod/github.com/juicedata/cli/v2@v2.19.4-0.20230605075551-9c9c5c0dce83/app.go:389 +0x1069 fp=0xc0014c1d08 sp=0xc0014c1a28 pc=0x6661c9
github.com/urfave/cli/v2.(*App).Run(...)
	/home/sam/go/pkg/mod/github.com/juicedata/cli/v2@v2.19.4-0.20230605075551-9c9c5c0dce83/app.go:254
github.com/juicedata/juicefs/cmd.Main({0xc000052180, 0x8, 0x8})
	/home/sam/src/juicefs/cmd/main.go:101 +0x3729 fp=0xc0014c1f00 sp=0xc0014c1d08 pc=0x266e149
main.main()
	/home/sam/src/juicefs/main.go:29 +0x28 fp=0xc0014c1f40 sp=0xc0014c1f00 pc=0x26a5e28
runtime.main()
	/usr/lib/go-1.21/src/runtime/proc.go:267 +0x2bb fp=0xc0014c1fe0 sp=0xc0014c1f40 pc=0x441e1b
runtime.goexit()
	/usr/lib/go-1.21/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0014c1fe8 sp=0xc0014c1fe0 pc=0x476181
```

We are on Gluster 11. We can't downgrade to Gluster <10.4 because we are on Ubuntu Mantic and there aren't packages at that version.

Is there a way to work around this or fix it?

**Comment by galchinsky** [comment]
Same here, 11.0, 11.2, 10.5 crashed, downgraded to 10.0.
If you don't want to fix it, please write the compatible version to the docs, it would save me a few hours
