### ISSUE TITLE
redis i/o timeout

### ISSUE THREAD

**Issue by anzuo09** [juicedata/juicefs#4055]
**What happened**:
Flink reported Redis I/O timeout when writing to Juicefs

```txt

2023-09-19 07:40:56,704 INFO  org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl      [] - [persistent://spe/cloud/specloud-partition-2] [spe-a-ssr-raw-pulsar-cloud-flink-test] [8fc8a] Prefetched messages: 0 --- Consume throughput received: 2.08 msgs/s --- 0.01 Mbit/s --- Ack sent rate: 0.00 ack/s --- Failed messages: 0 --- batch messages: 0 ---Failed acks: 0
2023/09/19 07:41:38.234723 juicefs[1] <WARNING>: Secret key is removed for the sake of safety [redis.go:3920]
2023-09-19 07:41:38,235 WARN  io.juicefs.JuiceFileSystemImpl                               [] - 2023/09/19 07:41:38.234723 juicefs[1] <WARNING>: Secret key is removed for the sake of safety [redis.go:3920]
.
.
.
2023/09/19 07:42:13.158529 juicefs[1] <ERROR>: error: read tcp 100.69.250.219:36576->100.122.169.211:6379: i/o timeout
goroutine 17778 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x7f0a026b34a0, 0xc0007c8190})
	/go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:122 +0xad
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).Write(0xc0007c80f0, {0x7f0a026e30a8?, 0xc0007aae80}, 0x71e44, 0x0, 0x0, {0x83b09, 0x3838, 0x0, 0x3838}, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/redis.go:2281 +0x55e
github.com/juicedata/juicefs/pkg/vfs.(*chunkWriter).commitThread(0xc05a1b3b90)
	/go/src/github.com/juicedata/juicefs/pkg/vfs/writer.go:202 +0x223
created by github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).writeChunk
	/go/src/github.com/juicedata/juicefs/pkg/vfs/writer.go:271 +0x3ed [utils.go:122]
2023/09/19 07:42:13.158590 juicefs[1] <WARNING>: write inode:466500 error: input/output error [writer.go:209]
2023/09/19 07:42:13.158603 juicefs[1] <ERROR>: write inode:466500 indx:0  input/output error [writer.go:213]
2023-09-19 07:42:13,158 ERROR io.juicefs.JuiceFileSystemImpl                               [] - 2023/09/19 07:42:13.158529 juicefs[1] <ERROR>: error: read tcp 100.69.250.219:36576->100.122.169.211:6379: i/o timeout
goroutine 17778 [running]:
runtime/debug.Stack()
	/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x7f0a026b34a0, 0xc0007c8190})
	/go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:122 +0xad
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).Write(0xc0007c80f0, {0x7f0a026e30a8?, 0xc0007aae80}, 0x71e44, 0x0, 0x0, {0x83b09, 0x3838, 0x0, 0x3838}, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/redis.go:2281 +0x55e
github.com/juicedata/juicefs/pkg/vfs.(*chunkWriter).commitThread(0xc05a1b3b90)
	/go/src/github.com/juicedata/juicefs/pkg/vfs/writer.go:202 +0x223
created by github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).writeChunk
	/go/src/github.com/juicedata/juicefs/pkg/vfs/writer.go:271 +0x3ed [utils.go:122]
2023-09-19 07:42:13,159 WARN  io.juicefs.JuiceFileSystemImpl                               [] - 2023/09/19 07:42:13.158590 juicefs[1] <WARNING>: write inode:466500 error: input/output error [writer.go:209]
2023-09-19 07:42:13,159 ERROR io.juicefs.JuiceFileSystemImpl                               [] - 2023/09/19 07:42:13.158603 juicefs[1] <ERROR>: write inode:466500 indx:0  input/output error [writer.go:213]
2023-09-19 07:42:13,343 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - IcebergStreamWriter (3/3)#0 (c06355b9ec8ee68d74c22dfe6dc987d5) switched from RUNNING to FAILED with failure cause: java.io.IOException: Could not perform checkpoint 134 for operator IcebergStreamWriter (3/3)#0.
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1210)
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointBarrierHandler.notifyCheckpoint(CheckpointBarrierHandler.java:147)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.triggerCheckpoint(SingleCheckpointBarrierHandler.java:287)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.access$100(SingleCheckpointBarrierHandler.java:64)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler$ControllerImpl.triggerGlobalCheckpoint(SingleCheckpointBarrierHandler.java:493)
	at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.triggerGlobalCheckpoint(AbstractAlignedBarrierHandlerState.java:74)
	at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.barrierReceived(AbstractAlignedBarrierHandlerState.java:66)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.lambda$processBarrier$2(SingleCheckpointBarrierHandler.java:234)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.markCheckpointAlignedAndTransformState(SingleCheckpointBarrierHandler.java:262)
	at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.processBarrier(SingleCheckpointBarrierHandler.java:231)
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.handleEvent(CheckpointedInputGate.java:181)
	at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.pollNext(CheckpointedInputGate.java:159)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:110)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:519)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:804)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:753)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: jfs://jfs/data/scene_type=DPI_SPE_A_SSR_ED/site_code=CZD3/day_tag=20230913/00002-0-aa5ae5ca-5c7d-4e98-97e1-a10f58f6e7f6-00803.parquet
	at io.juicefs.JuiceFileSystemImpl.error(JuiceFileSystemImpl.java:281)
	at io.juicefs.JuiceFileSystemImpl.access$600(JuiceFileSystemImpl.java:76)
	at io.juicefs.JuiceFileSystemImpl$FSOutputStream.close(JuiceFileSystemImpl.java:1018)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at io.juicefs.JuiceFileSystemImpl$BufferedFSOutputStream.close(JuiceFileSystemImpl.java:1139)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.util.HadoopPositionOutputStream.close(HadoopPositionOutputStream.java:64)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:1197)
	at org.apache.iceberg.parquet.ParquetWriter.close(ParquetWriter.java:255)
	at org.apache.iceberg.io.DataWriter.close(DataWriter.java:82)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.closeCurrent(BaseTaskWriter.java:314)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.close(BaseTaskWriter.java:341)
	at org.apache.iceberg.io.PartitionedFanoutWriter.close(PartitionedFanoutWriter.java:70)
	at org.apache.iceberg.io.BaseTaskWriter.complete(BaseTaskWriter.java:96)
	at org.apache.iceberg.flink.sink.IcebergStreamWriter.flush(IcebergStreamWriter.java:111)
	at org.apache.iceberg.flink.sink.IcebergStreamWriter.prepareSnapshotPreBarrier(IcebergStreamWriter.java:66)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.prepareSnapshotPreBarrier(RegularOperatorChain.java:89)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:300)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$12(StreamTask.java:1253)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1241)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1198)
	... 22 more
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.1.0

**Comment by anzuo09** [comment]
I saw Juicefs reporting `Secret key is removed`, and I feel like it caused `Redis timeout`
![image](https://github.com/juicedata/juicefs/assets/106730199/9e3216bf-fb84-4eef-879a-d66bb9d62a8a)

**Comment by SandyXSD** [comment]
This log is printed when dumping metadata. So the timeout issue is probably caused by metadata backup, which indeed may cause pressure spike to the metadata engine. See https://juicefs.com/docs/community/metadata_dump_load/#backup-automatically for details.
