### ISSUE TITLE
use juicefs with hadoop on window10 throw java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zhuyinjun** [juicedata/juicefs#4154]
<dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>3.3.3</version>
        </dependency>
        <dependency>
            <groupId>io.juicefs</groupId>
            <artifactId>juicefs-hadoop</artifactId>
            <version>1.1.0</version>
        </dependency>

 public static void main(String[] args) throws Exception {
//        System.out.println(System.getenv("Path"));
        Configuration conf = new Configuration();
        conf.set("fs.jfs.impl", "io.juicefs.JuiceFileSystem");
        conf.set("fs.AbstractFileSystem.jfs.impl","com.juicefs.JuiceFS");
        conf.set("juicefs.meta", "sqlite:\\myjfs.db");  // JuiceFS 元数据引擎地址
        Path p = new Path("jfs://test2/");  // 请替换 {JFS_NAME} 为正确的值
        FileSystem jfs = p.getFileSystem(conf);
//        FSDataOutputStream dataInputStream=jfs.create(p);
//        dataInputStream.write("dwwdwdd".getBytes(StandardCharsets.UTF_8));
//        dataInputStream.close();
        FileStatus[] fileStatuses = jfs.listStatus(p);
        // 遍历 JuiceFS 文件系统并打印文件路径
        for (FileStatus status : fileStatuses) {
            System.out.println(status.getPath());
        }
    }

According to the demo on the official website，i get this error，I don't know how to solve this problem
 
Exception in thread "main" java.lang.UnsatisfiedLinkError: unknown
Library names
[D:\temp\libjfs-amd64.12.dll]
Search paths:
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:111)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:85)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:64)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:74)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:141)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:87)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:420)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:399)
	at io.juicefs.JuiceFileSystemImpl.loadLibrary(JuiceFileSystemImpl.java:673)
	at io.juicefs.JuiceFileSystemImpl.initialize(JuiceFileSystemImpl.java:350)
	at org.apache.hadoop.fs.FilterFileSystem.initialize(FilterFileSystem.java:98)
	at io.juicefs.JuiceFileSystem.initialize(JuiceFileSystem.java:69)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at operator.TestRest.main(TestRest.java:18)

**Comment by zhuyinjun** [comment]
Is there any progress here

**Comment by tangyoupeng** [comment]
Did you build the jar by your self or download from the release page?
