### ISSUE TITLE
use source code to compile juicefs-hadoop-client.jar is only 33.44MB, too less than the public jar, can't start hadoop

### ISSUE THREAD

**Issue by mupengfeilove** [juicedata/juicefs#4209]

**Comment by tangyoupeng** [comment]
The published jar contains multiple platform libjfs.so in the jar. Self compiled jar only contains one platform and only works for that platform. For example, if you want to runs in centos7, it'll be better compile the jar with centos7

**Comment by mupengfeilove** [comment]
I compiled the jar in same system platform but it need download some lib from java.sun.com while use the result jar,but we use juicefs in LAN. how to solve this problem? error info like this:


2023-11-29 16:28:58,530 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Shutdown complete.
2023-11-29 16:28:58,530 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: Exception in secureMain
java.io.IOException: Unable to initialize WebAppContext
7098b907{/static,jar:file:/usr/local/hadoop-3.2.0/share/hadoop/common/lib/juicefs-hadoop-1.1.0
.jar!/webapps/static,UNAVAILABLE}
2023-11-29 16:28:58,476 INFO org.eclipse.jetty.server.handler.ContextHandler: Stopped o.e.j.s.ServletContextHandler@147e2ae7{/logs,file:///usr/local/hadoop-3.2.0/logs/,UNAVAILABLE}
2023-11-29 16:28:58,530 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Shutdown complete.
2023-11-29 16:28:58,530 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: Exception in secureMain
java.io.IOException: Unable to initialize WebAppContext
        at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1162)
        at org.apache.hadoop.hdfs.server.datanode.web.DatanodeHttpServer.<init>(DatanodeHttpServer.java:141)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.startInfoServer(DataNode.java:957)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.startDataNode(DataNode.java:1417)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.<init>(DataNode.java:500)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:2782)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2690)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2732)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2876)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2900)
Caused by: java.net.UnknownHostException: java.sun.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1270)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:264)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1161)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentSc
annerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:255)
        at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:54)
        at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:207)
        at org.eclipse.jetty.webapp.MetaData.setWebXml(MetaData.java:189)
        at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:60)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:485)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:521)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:427)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:394)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1140)
        ... 9 more
2023-11-29 16:28:58,532 INFO org.apache.hadoop.util.ExitUtil: Exiting with status 1: java.io.IOException: Unable to 
initialize WebAppContext
2023-11-29 16:28:58,533 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: SHUTDOWN_MSG:

**Comment by tangyoupeng** [comment]
Seems it is the hdfs datanode problem.

**Comment by mupengfeilove** [comment]
But this problem only happen when use self compile jar. it dosn't happen when use public jar.

**Comment by mupengfeilove** [comment]
2023-11-29 16:28:58,530 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: Exception in secureMain
java.io.IOException: Unable to initialize WebAppContext
7098b907{/static,jar:file:/usr/local/hadoop-3.2.0/share/hadoop/common/lib/juicefs-hadoop-1.1.0
.jar!/webapps/static,UNAVAILABLE}

this is relation to juicefs-hadoop-1.1.0.jar.

**Comment by mupengfeilove** [comment]
Maybe juicefs-hadoop-1.1.0.jar want to download something from  java.sun.com but the develop environment is LAN. 
So I can't download.So weather juicefs-hadoop-1.1.0.jar will download something from  java.sun.com?

**Comment by tangyoupeng** [comment]
How to reproduce this?

**Comment by mupengfeilove** [comment]
1、Deploy the juicefs client in the Hadoop based on the official document.
2、use source code to compile a  juicefs-hadoop-1.1.0.jar in single platform, then Replace the  juicefs-hadoop-1.1.0.jar in the Hadoop environment where the Juicefs client has been deployed.
3、restart hadoop and see datanode log.
