### ISSUE TITLE
When using MySQL as the metadata engine, an issue arises with the 'jfs_node' node type.

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#4229]
### Discussed in https://github.com/juicedata/juicefs/discussions/4225

<div type='discussions-op-text'>

<sup>Originally posted by **sinmem** December  1, 2023</sup>
While the system automatically initializes the file system, the 'uid' and 'gid' within the 'node' are initially set as 'int'. However, file uploads via the gateway require 'bigint', resulting in upload failures that necessitate manual modification. Is this a software bug or an operational mistake?
version: juicefs-1.1.1-windows-amd64.tar.gz
![image](https://github.com/juicedata/juicefs/assets/37241398/ffc848ee-6cd5-414e-8c1b-b9c2b67de831)
```bash
2023/12/01 13:13:49.526515 juicefs[42588] <ERROR>: error: Error 1264 (22003): Out of range value for column 'uid' at row 1
goroutine 291 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3e43be0, 0xc0024fa108})
        /go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:122 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc000e54960, {0x3e78638, 0xc001db2200}, 0x1, {0xc002234871, 0x4}, 0x2, 0x1ff, 0x12, 0x0, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/sql.go:1226 +0x2a5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc00028aa00, {0x3e78638, 0xc001db2200}, 0x1, {0xc002234871, 0x4}, 0x8?, 0x0?, 0x0?, 0x0, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:1352 +0x2d5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0xc00028aa00, {0x3e78638?, 0xc001db2200?}, 0x1, {0xc002234871?, 0x3e78638?}, 0x2200?, 0x1db?, 0xc0?, 0xc0025ca538, ...)
        /go/src/github.com/juicedata/juicefs/pkg/meta/base.go:1376 +0x78
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Mkdir(0xc001dba000, {0x3e78638?, 0xc001db2200}, {0xc002234870, 0x5}, 0x1ff, 0x4a?)
        /go/src/github.com/juicedata/juicefs/pkg/fs/fs.go:441 +0x376
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).mkdirAll(0xc001d94420, {0x3e642c8, 0xc000c46100}, {0xc002234870, 0x5})
        /go/src/github.com/juicedata/juicefs/pkg/gateway/gateway.go:638 +0xf3
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).mkdirAll(0xc001d94420, {0x3e642c8, 0xc000c46100}, {0xc002234870, 0x9})
        /go/src/github.com/juicedata/juicefs/pkg/gateway/gateway.go:640 +0x14d
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).putObject(0xc001d94420, {0x3e642c8, 0xc000c46100}, {0xc0021a5872, 0x5}, {0xc00227f448, 0x8}, _, {{0x0, 0x0}, ...})
        /go/src/github.com/juicedata/juicefs/pkg/gateway/gateway.go:658 +0x1d1
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).PutObject(_, {_, _}, {_, _}, {_, _}, _, {{0x0, 0x0}, ...})
        /go/src/github.com/juicedata/juicefs/pkg/gateway/gateway.go:731 +0x3ae
github.com/minio/minio/cmd.(*webAPIHandlers).Upload(0xc00027e220, {0x3e5aa90, 0xc00207a5a0}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/web-handlers.go:1321 +0x16e3
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2084
github.com/minio/minio/cmd.httpTraceHdrs.func1({0x3e5aa90?, 0xc00207a5a0?}, 0x8?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/handler-utils.go:371 +0x53
net/http.HandlerFunc.ServeHTTP(0xc00208b300?, {0x3e5aa90?, 0xc00207a5a0?}, 0xa0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setRedirectHandler.func1({0x3e5aa90, 0xc00207a5a0}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:135 +0x147
net/http.HandlerFunc.ServeHTTP(0x3e5aa60?, {0x3e5aa90?, 0xc00207a5a0?}, 0x10?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.addCustomHeaders.func1({0x3e5aa60, 0xc0010aff08}, 0xc00109cc60?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:660 +0x136
net/http.HandlerFunc.ServeHTTP(0x343e720?, {0x3e5aa60?, 0xc0010aff08?}, 0x17?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.addSecurityHeaders.func1({0x3e5aa60, 0xc0010aff08}, 0x0?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:669 +0x184
net/http.HandlerFunc.ServeHTTP(0x0?, {0x3e5aa60?, 0xc0010aff08?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setBucketForwardingHandler.func1({0x3e5aa60, 0xc0010aff08}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:543 +0x237
net/http.HandlerFunc.ServeHTTP(0xc0021a5864?, {0x3e5aa60?, 0xc0010aff08?}, 0x47a2f3?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setRequestValidityHandler.func1({0x3e5aa60, 0xc0010aff08}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:531 +0x394
net/http.HandlerFunc.ServeHTTP(0xc0025b4660?, {0x3e5aa60?, 0xc0010aff08?}, 0x90108?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setHTTPStatsHandler.func1({0x3e623b0?, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:465 +0x11f
net/http.HandlerFunc.ServeHTTP(0x2eb61b0?, {0x3e623b0?, 0xc00025eb60?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1({0x3e623b0?, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:49 +0x102
net/http.HandlerFunc.ServeHTTP(0xc0010b8a70?, {0x3e623b0?, 0xc00025eb60?}, 0xc0025b4900?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:68 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc0021ecf00?, {0x3e623b0?, 0xc00025eb60?}, 0xc0010afed8?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP({{0x3e4e460?, 0xc0010afde8?}}, {0x3e623b0?, 0xc00025eb60?}, 0x1b?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/crossdomain-xml-handler.go:51 +0xef
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:161 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc00208b300?, {0x3e623b0?, 0xc00025eb60?}, 0x3e30dec?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setReservedBucketHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:293 +0x2c2
net/http.HandlerFunc.ServeHTTP(0xc0021ed0b8?, {0x3e623b0?, 0xc00025eb60?}, 0xc0025b4660?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:262 +0x2b7
net/http.HandlerFunc.ServeHTTP(0xc00208b300?, {0x3e623b0?, 0xc00025eb60?}, 0x30?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setTimeValidityHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:357 +0x3a3
net/http.HandlerFunc.ServeHTTP(0xc00208b300?, {0x3e623b0?, 0xc00025eb60?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setIgnoreResourcesHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:452 +0x337
net/http.HandlerFunc.ServeHTTP(0xc00208b300?, {0x3e623b0?, 0xc00025eb60?}, 0xc0021ed4e8?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setAuthHandler.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/auth-handler.go:504 +0x2a9
net/http.HandlerFunc.ServeHTTP(0x35a3000?, {0x3e623b0?, 0xc00025eb60?}, 0x39?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.setSSETLSHandler.func1({0x3e623b0?, 0xc00025eb60?}, 0xc00208b300?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:703 +0x3ca
net/http.HandlerFunc.ServeHTTP(0x90?, {0x3e623b0?, 0xc00025eb60?}, 0xc0010afea8?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.filterReservedMetadata.func1({0x3e623b0, 0xc00025eb60}, 0xc00208b300)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:108 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc00208b200?, {0x3e623b0?, 0xc00025eb60?}, 0xc0025aa880?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0009675c0, {0x3e623b0, 0xc00025eb60}, 0xc0024b4600)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x3e623b0, 0xc00025eb60}, 0xc0024b4600)
        /go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc000c47040?, {0x3e623b0?, 0xc00025eb60?}, 0x5463bc0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP({{0x3e4e460?, 0xc000e544e0?}}, {0x3e623b0?, 0xc00025eb60?}, 0x0?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/generic-handlers.go:688 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1({0x3e623b0?, 0xc00025eb60?}, 0xc0025aa810?)
        /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20221113011458-8866d5c9df8c/cmd/http/server.go:101 +0x1ba
net/http.HandlerFunc.ServeHTTP(0x0?, {0x3e623b0?, 0xc00025eb60?}, 0x40ef65?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0x3e563f0?}, {0x3e623b0, 0xc00025eb60}, 0xc0024b4600)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000e4be00, {0x3e64370, 0xc000df2150})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db [utils.go:122]
2023/12/01 13:13:49.528884 juicefs[42588] <ERROR>: create /.sys/tmp/1b9c312e-acd0-4f8d-bb6f-902e203f4994: The system cannot find the file specified. [gateway.go:662]

API: SYSTEM(bucket=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5, object=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5)
Time: 13:13:49 CST 12/01/2023
DeploymentID: ad15981e-8e29-4016-ad02-e3c2cb3aec4a
RemoteHost: 5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5
Error: syscall.Errno
       3: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\web-handlers.go:2428:cmd.toWebAPIError()
       2: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\web-handlers.go:2438:cmd.writeWebErrorResponse()
       1: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\web-handlers.go:1323:cmd.(*webAPIHandlers).Upload()

API: SYSTEM(bucket=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5, object=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5)
Time: 13:13:49 CST 12/01/2023
DeploymentID: ad15981e-8e29-4016-ad02-e3c2cb3aec4a
RemoteHost: 5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5
Error: syscall.Errno
       5: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\api-errors.go:2006:cmd.toAPIErrorCode()
       4: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\api-errors.go:2031:cmd.toAPIError()
       3: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\web-handlers.go:2429:cmd.toWebAPIError()
       2: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\web-handlers.go:2438:cmd.writeWebErrorResponse()
       1: \go\pkg\mod\github.com\juicedata\minio@v0.0.0-20221113011458-8866d5c9df8c\cmd\web-handlers.go:1323:cmd.(*webAPIHandlers).Upload()
```
</div>

**Comment by zhijian-pro** [comment]
Currently, the uid and gid of more than int32 are not supported. 
Is the uid of such a large size specially set by yourself ?

**Comment by masx200** [comment]
```text
2025/05/14 03:26:28.148397 juicefs[26316] <INFO>: Meta address: mysql://storage:****@(10.200.200.2:3306)/storage [interface.go:504]
2025/05/14 03:26:28.170624 juicefs[26316] <INFO>: Data use webdav://10.200.200.2:5244/mysql-storage/ [gateway.go:230]
2025/05/14 03:26:28.171155 juicefs[26316] <INFO>: Disk cache (C:\Windows\system32\config\systemprofile\.juicefs\cache\9ae1bcb1-1470-492f-aa48-36622302d253\): capacity (100 GiB), free ratio 10%, used ratio - [space 70.4%, inode 0%], max pending pages 15 [disk_cache.go:144]
2025/05/14 03:26:28.279235 juicefs[26316] <INFO>: Create session 10 OK with version: 1.2.3+2025-01-22.4f2aba8 [base.go:398]
2025/05/14 03:26:28.292687 juicefs[26316] <INFO>: Prometheus metrics listening on 127.0.0.1:9567 [mount.go:135]
2025/05/14 03:26:28.292687 juicefs[26316] <INFO>: WebDAV listening on 0.0.0.0:49999 [http.go:241]
2025/05/14 03:28:38.761665 juicefs[26316] <ERROR>: error: Error 1264 (22003): Out of range value for column 'uid' at row 1
goroutine 104 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/juicedata/juicefs/pkg/meta.errno({0x143a831c0, 0xc001996180})
	/go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:123 +0xad
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc0008a0360, {0x143abe428?, 0xc00193cc00?}, 0x1, {0xc000052427?, 0xc00193cc00?}, 0x1?, 0x1ff, 0x0?, {0x0, ...}, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/sql.go:1268 +0x12b
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc000124000, {0x143abe428, 0xc00193cc00}, 0x1, {0xc000052427, 0x8}, 0x2, 0x0?, 0x0?, 0x0, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/base.go:1018 +0x3e4
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0xc000124000, {0x143abe428?, 0xc00193cc00?}, 0x1, {0xc000052427?, 0x14294ec40?}, 0x3601?, 0x400a?, 0x1?, 0xc001659750, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/base.go:1042 +0x72
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Mkdir(0xc000fc28c0, {0x143abe428?, 0xc00193cc00}, {0xc000052426, 0xa}, 0x1ff, 0x0?)
	/go/src/github.com/juicedata/juicefs/pkg/fs/fs.go:444 +0x3d4
github.com/juicedata/juicefs/pkg/fs.(*webdavFS).Mkdir(0xc00193cc80?, {0xc000d3a400?, 0xc000052426?}, {0xc000052426?, 0x0?}, 0x0?)
	/go/src/github.com/juicedata/juicefs/pkg/fs/http.go:91 +0x2b
golang.org/x/net/webdav.(*Handler).handleMkcol(0xc00193cc80, {0x1?, 0xc00166ba40?}, 0xc000d3a400)
	/go/pkg/mod/golang.org/x/net@v0.23.0/webdav/webdav.go:309 +0x1d8
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc00193cc80, {0x143a9c620, 0xc000d79dc0}, 0xc000d3a400)
	/go/pkg/mod/golang.org/x/net@v0.23.0/webdav/webdav.go:60 +0x18e
github.com/juicedata/juicefs/pkg/fs.(*indexHandler).ServeHTTP(0xc00193a480, {0x143a9c620, 0xc000d79dc0}, 0xc000d3a400)
	/go/src/github.com/juicedata/juicefs/pkg/fs/http.go:219 +0x4d6
net/http.(*ServeMux).ServeHTTP(0x14530d400?, {0x143a9c620, 0xc000d79dc0}, 0xc000d3a400)
	/usr/local/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc000cda720?}, {0x143a9c620?, 0xc000d79dc0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000d1c5a0, {0x143aa8e20, 0xc001927d10})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3086 +0x5cb [utils.go:123]
2025/05/14 03:28:38.761665 juicefs[26316] <ERROR>: WEBDAV [MKCOL]: /20250505/, ERROR: input/output error [http.go:230]
```

**Comment by michael-newsrx** [comment]
Still an active issue with juicefs installed via curl, version: `1.3.1`

```go
=> juicefs.log <==
2025/12/03 11:38:59.973619 juicefs[1663] <ERROR>: error: Error 1264 (22003): Out of range value for column 'uid' at row 1
goroutine 28 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/juicedata/juicefs/pkg/meta.errno({0x4a39e00, 0xc001f62168})
	/go/src/github.com/juicedata/juicefs/pkg/meta/utils.go:127 +0xad
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0x1?, {0x4a994d8?, 0xc001242140?}, 0x3526900?, {0xc001ed29e6?, 0xc002db1ad8?}, 0x3c?, 0x1ff, 0x0?, {0x0, ...}, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/sql.go:1604 +0xef
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mknod(0xc001320000, {0x4a994d8, 0xc001242140}, 0x7, {0xc001ed29e6, 0xa}, 0x2, 0x2db?, 0xc0?, 0x0, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/base.go:1231 +0x4c4
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Mkdir(0xc001320000, {0x4a994d8?, 0xc001242140?}, 0x7, {0xc001ed29e6?, 0x3c37ec0?}, 0x1c00?, 0x41?, 0x0?, 0xc001ed2a10, ...)
	/go/src/github.com/juicedata/juicefs/pkg/meta/base.go:1255 +0x72
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Mkdir(0xc00055c0a0, {0x4a9c180?, 0xc001242140}, 0x7, {0xc001ed29e6, 0xa}, 0x1ff, 0x133?)
	/go/src/github.com/juicedata/juicefs/pkg/vfs/vfs.go:297 +0x21c
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Mkdir(0xc001796ba0, 0x3064125?, 0xc0013343f0, {0xc001ed29e6, 0xa}, 0x41a5a8?)
	/go/src/github.com/juicedata/juicefs/pkg/fuse/fuse.go:139 +0xce
github.com/hanwen/go-fuse/v2/fuse.doMkdir(0xc0017ec000?, 0xc001334240)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20250509085345-58f40c5d2ed9/fuse/opcode.go:386 +0x67
github.com/hanwen/go-fuse/v2/fuse.init.1.func1(0x1a00000068?, 0x2?)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20250509085345-58f40c5d2ed9/fuse/opcode.go:808 +0x49
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0017ec000, 0xc001334240)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20250509085345-58f40c5d2ed9/fuse/server.go:815 +0x2f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0017ec000, 0x0?)
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20250509085345-58f40c5d2ed9/fuse/server.go:788 +0x110
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest in goroutine 1
	/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20250509085345-58f40c5d2ed9/fuse/server.go:451 +0x6ab [errno@utils.go:127]
```

**Comment by zhijian-pro** [comment]
> It can be made to work by manually repairing the table structure, which is a workaround to the solution.
> 
> ```
> ALTER TABLE jfs_node
> MODIFY uid bigint;
> ALTER TABLE jfs_node
> MODIFY gid bigint;
> ```

Can this plan solve your problem?

**Comment by michael-newsrx** [comment]
It solves it, but I was lucky to find the solution. I had no idea what was
going on, the juicefs sits behind Samba, the windows system was just saying
things about "an error" when trying to create folders.

**Comment by stevefan1999-personal** [comment]
https://github.com/juicedata/juicefs/blob/e0d5ec1dcc416cc9cbf2a2cc7dbf9e299b4bbee0/pkg/meta/sql.go#L77-L78

Seems like we should teel xorm to map this to BIGINT on mysql
