### ISSUE TITLE
juicesync exclude pattern match incorrect.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4463]
**What happened**:
```
root@bench-01:~/juicefs# python3 .github/scripts/hypo/syncrand_test.py -k test_sync7
setup_logger ./syncrand.log
2024-03-07 22:35:41,647 - INFO - do_create_file /tmp/sync_src/aa with mode w succeed
2024-03-07 22:35:41,648 - INFO - do_create_file /tmp/sync_src2/aa with mode w succeed
2024-03-07 22:35:41,650 - INFO - rsync -r -vvv /tmp/sync_src/ /tmp/rsync/ --exclude aa**a
2024-03-07 22:35:41,652 - INFO - ./juicefs sync --dirs -v /tmp/sync_src/ /tmp/juicesync/ --exclude aa**a
Only in /tmp/rsync: aa
Command '['diff', '-r', '/tmp/rsync', '/tmp/juicesync']' returned non-zero exit status 1.
E
======================================================================
ERROR: test_sync7 (__main__.TestFsrand2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".github/scripts/hypo/syncrand_test.py", line 57, in test_sync7
    state.sync(options=[{'option': '--exclude', 'pattern': 'aa**a'}])
  File "/root/juicefs/.github/scripts/hypo/syncrand.py", line 104, in sync
    )
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 681, in rule_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/syncrand.py", line 117, in sync
    raise e
  File "/root/juicefs/.github/scripts/hypo/syncrand.py", line 114, in sync
    subprocess.check_call(['diff', '-r', self.DEST_RSYNC, self.DEST_JUICESYNC])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['diff', '-r', '/tmp/rsync', '/tmp/juicesync']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 1 test in 0.045s

FAILED (errors=1)

root@bench-01:~/juicefs# tree /tmp/sync_src/ /tmp/rsync/ /tmp/juicesync/
/tmp/sync_src/
└── aa
/tmp/rsync/
└── aa
/tmp/juicesync/

0 directories, 2 files
root@bench-01:~/juicefs#
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by jiefenghuang** [comment]
fix: [add dontumask](https://github.com/juicedata/juicefs/pull/4443/commits/8c86874a70a24873a55b22813b319534e58473db)

**Comment by jiefenghuang** [comment]
ignore commit 8c86874 and f17cd99

**Comment by zhijian-pro** [comment]
The same case
<img width="1826" alt="image" src="https://github.com/juicedata/juicefs/assets/31313340/26296c40-c2bf-4a72-a84b-621414cd5775">
