### ISSUE TITLE
setfacl: Operation not supported

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4465]
**What happened**:
Code to Reproduce:
```
    def test_acl(self):
        state = JuicefsMachine()
        v1 = state.init_folders()
        v2 = state.create_file(content=b'', file_name='stsn', mode='x', parent=v1, umask=464, user='root')
        state.set_acl(default=True, entry=v2, group='user1', group_perm={'r', 'w', 'x'}, logical=False, mask={'r', 'w', 'x'}, not_recalc_mask=False, other_perm={'r'}, physical=False, recalc_mask=True, recursive=False, set_mask=False, sudo_user='user1', user='user1', user_perm=set())
        state.create_file(content=b'', file_name='vbcx', mode='a', parent=v1, umask=154, user='user1')
        v6 = state.create_file(content=b'w\xb1', file_name='sctj', mode='w', parent=v1, umask=376, user='root')
        state.set_acl(default=False, entry=v6, group='group3', group_perm={'w'}, logical=False, mask={'w', 'x'}, not_recalc_mask=False, other_perm=set(), physical=False, recalc_mask=False, recursive=True, set_mask=True, sudo_user='root', user='root', user_perm=set())
        state.set_acl(default=True, entry=v1, group='user3', group_perm={'r', 'w', 'x'}, logical=False, mask={'x'}, not_recalc_mask=True, other_perm=set(), physical=False, recalc_mask=True, recursive=False, set_mask=False, sudo_user='user1', user='user3', user_perm=set())
        state.teardown()
```

Run Log:
```
root@bench-01:~/juicefs# python3 .github/scripts/hypo/fsrand2_test.py -k test_acl
setup_logger ./log1
setup_logger ./log2
__init__
duration is 0.029043197631835938
2024-03-08 16:03:27,014 - INFO - do_create_file /tmp/fsrand/stsn with mode x succeed
2024-03-08 16:03:27,018 - INFO - do_create_file /tmp/jfs/fsrand/stsn with mode x succeed
2024-03-08 16:03:27,018 - INFO - run_cmd: sudo -u user1 setfacl -d  --mask    -m u:user1:-,g:user1:rwx,o::r /tmp/fsrand/stsn
2024-03-08 16:03:27,024 - INFO - do_set_acl /tmp/fsrand/stsn {'user_perm': '-', 'group_perm': 'rwx', 'other_perm': 'r'} failed:
setfacl: /tmp/fsrand/stsn: Only directories can have default ACLs
2024-03-08 16:03:27,024 - INFO - run_cmd: sudo -u user1 setfacl -d  --mask    -m u:user1:-,g:user1:rwx,o::r /tmp/jfs/fsrand/stsn
2024-03-08 16:03:27,028 - INFO - do_set_acl /tmp/jfs/fsrand/stsn {'user_perm': '-', 'group_perm': 'rwx', 'other_perm': 'r'} failed:
setfacl: /tmp/jfs/fsrand/stsn: Only directories can have default ACLs
2024-03-08 16:03:27,029 - INFO - do_create_file /tmp/fsrand/vbcx {'mode': 'a', 'user': 'user1'} failed: [Errno 1] Operation not permitted
2024-03-08 16:03:27,029 - INFO - do_create_file /tmp/jfs/fsrand/vbcx {'mode': 'a', 'user': 'user1'} failed: [Errno 1] Operation not permitted
2024-03-08 16:03:27,029 - INFO - do_create_file /tmp/fsrand/sctj with mode w succeed
2024-03-08 16:03:27,032 - INFO - do_create_file /tmp/jfs/fsrand/sctj with mode w succeed
2024-03-08 16:03:27,032 - INFO - run_cmd: sudo -u root setfacl  -R     -m u:root:-,g:group3:w,o::-,m::wx /tmp/fsrand/sctj
run_cmd:getfacl /tmp/fsrand/sctj
2024-03-08 16:03:27,038 - INFO - do_set_acl /tmp/fsrand/sctj with u:root:-,g:group3:w,o::-,m::wx succeed
2024-03-08 16:03:27,038 - INFO - run_cmd: sudo -u root setfacl  -R     -m u:root:-,g:group3:w,o::-,m::wx /tmp/jfs/fsrand/sctj
2024-03-08 16:03:27,042 - INFO - do_set_acl /tmp/jfs/fsrand/sctj {'user_perm': '-', 'group_perm': 'w', 'other_perm': '-'} failed:
setfacl: /tmp/jfs/fsrand/sctj: Operation not supported
F
======================================================================
FAIL: test_1 (__main__.TestFsrand2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".github/scripts/hypo/fsrand2_test.py", line 124, in test_1
    state.set_acl(default=False, entry=v6, group='group3', group_perm={'w'}, logical=False, mask={'w', 'x'}, not_recalc_mask=False, other_perm=set(), physical=False, recalc_mask=False, recursive=True, set_mask=True, sudo_user='root', user='root', user_perm=set())
  File "/root/juicefs/.github/scripts/hypo/fsrand2.py", line 418, in set_acl
    target=EntryWithACL,
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 681, in rule_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/fsrand2.py", line 418, in set_acl
    target=EntryWithACL,
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 802, in precondition_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/fsrand2.py", line 439, in set_acl
    assert self.equal(result1, result2), f'\033[31mset_acl:\nresult1 is {result1}\nresult2 is {result2}\033[0m'
AssertionError: set_acl:
result1 is ("getfacl: Removing leading '/' from absolute path names\n# owner: root\n# group: root\nuser::-w-\nuser:root:---\ngroup::---\ngroup:group3:-w-\nmask::-wx\nother::---\n\n",)
result2 is
setfacl: /tmp/jfs/fsrand/sctj: Operation not supported
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhoucheng361** [comment]
can't reproduce.
