### ISSUE TITLE
etag is empty with python minio sdk.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4615]
**What happened**:
```
root@bench-01:~/juicefs# git checkout test-gateway-randomly
root@bench-01:~/juicefs# ./juicefs format sqlite3://test.db xxx
root@bench-01:~/juicefs#MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin ./juicefs gateway sqlite3://test.db localhost:9005 --access-log access.log --keep-etag
root@bench-01:~/juicefs# mc alias set gateway http://localhost:9005 minioadmin minioadmin
root@bench-01:~/juicefs# python3 .github/scripts/hypo/s3_test.py
FAIL: test_s3 (__main__.TestS3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".github/scripts/hypo/s3_test.py", line 11, in test_s3
    state.list_objects('bucket1')
  File "/root/juicefs/.github/scripts/hypo/s3.py", line 93, in list_objects
    bucket_name = buckets.filter(lambda x: x != multiple()),
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 681, in rule_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/s3.py", line 93, in list_objects
    bucket_name = buckets.filter(lambda x: x != multiple()),
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 802, in precondition_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/s3.py", line 104, in list_objects
    assert result1 == result2, f'\033[31mlist_objects:\nresult1 is {result1}\nresult2 is {result2}\033[0m'
AssertionError: list_objects:
result1 is object1 14549 e72596d4a2887ee0ce3ed55ca2df5c02
object2 14549 e72596d4a2887ee0ce3ed55ca2df5c02
result2 is object1 14549
object2 14549

root@bench-01:~/juicefs# cat .github/scripts/hypo/s3_test.py
import unittest
from s3 import S3Machine
class TestS3(unittest.TestCase):
    def test_s3(self):
        state = S3Machine()
        state.create_bucket('bucket1')
        state.create_bucket('bucket2')
        state.put_object('bucket1', 'object1')
        state.put_object('bucket1', 'object2')
        state.list_objects('bucket1')
        state.list_objects('bucket2')
        state.remove_object('bucket1:object1')
        state.remove_object('bucket1:object2')
        state.teardown()

if __name__ == '__main__':
    unittest.main()
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhoucheng361** [comment]
fixed by https://github.com/juicedata/juicefs/pull/4617
