### ISSUE TITLE
should not able to set alias when user is disabled

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4660]
```
root@bench-01:~/juicefs# cat .github/scripts/hypo/s3_test.py
    def test_xxx(self):
        state = S3Machine()
        v1 = state.init_aliases()
        v2, v3, v4, v5 = state.init_policies()
        v8 = state.add_user(alias=v1, user_name='user1')
        state.disable_user(alias=v1, user_name=v8)
        v14 = state.add_user(alias=v1, user_name=v8)
        state.set_alias(alias='pjzm', url1='localhost:9000', url2='localhost:9006', user_name=v8)
        state.teardown()
root@bench-01:~/juicefs# python3 .github/scripts/hypo/s3_test.py -k test_xxx
setup_logger ./minio.log
setup_logger ./juice.log
2024-04-08 11:49:26,989 - INFO - run_cmd: mc alias list
2024-04-08 11:49:27,017 - INFO - do_list_aliases succeed
2024-04-08 11:49:27,017 - INFO - run_cmd: mc alias remove minio_admin
Alias 'minio_admin' removed successfully.
2024-04-08 11:49:27,043 - INFO - run_cmd: mc alias remove minio_pjzm
Alias 'minio_pjzm' removed successfully.
2024-04-08 11:49:27,069 - INFO - run_cmd: mc alias list
2024-04-08 11:49:27,096 - INFO - do_list_aliases succeed
2024-04-08 11:49:27,096 - INFO - run_cmd: mc alias remove juice_admin
Alias 'juice_admin' removed successfully.
2024-04-08 11:49:27,123 - INFO - run_cmd: mc alias set minio_admin http://localhost:9000 minioadmin minioadmin
2024-04-08 11:49:27,150 - INFO - do_set_alias admin localhost:9000 minioadmin minioadmin succeed
2024-04-08 11:49:27,151 - INFO - run_cmd: mc alias set juice_admin http://localhost:9005 minioadmin minioadmin
2024-04-08 11:49:27,179 - INFO - do_set_alias admin localhost:9005 minioadmin minioadmin succeed
2024-04-08 11:49:27,185 - INFO - run_cmd: mc admin user list minio_admin
2024-04-08 11:49:27,267 - INFO - run_cmd: mc admin user remove minio_admin user1
User 'user1' removed successfully.
2024-04-08 11:49:27,296 - INFO - run_cmd: mc admin user list juice_admin
2024-04-08 11:49:27,377 - INFO - run_cmd: mc admin user remove juice_admin user1
User 'user1' removed successfully.
2024-04-08 11:49:27,421 - INFO - run_cmd: mc admin group list minio_admin
2024-04-08 11:49:27,449 - INFO - run_cmd: mc admin group list juice_admin
2024-04-08 11:49:27,475 - INFO - run_cmd: mc admin policy list minio_admin
2024-04-08 11:49:27,503 - INFO - do_list_policies succeed
2024-04-08 11:49:27,503 - INFO - run_cmd: mc admin policy list juice_admin
2024-04-08 11:49:27,531 - INFO - do_list_policies succeed
2024-04-08 11:49:27,531 - INFO - run_cmd: mc admin user add minio_admin user1 minioadmin
2024-04-08 11:49:27,615 - INFO - do_add_user user1 succeed
2024-04-08 11:49:27,615 - INFO - run_cmd: mc admin user add juice_admin user1 minioadmin
2024-04-08 11:49:27,706 - INFO - do_add_user user1 succeed
2024-04-08 11:49:27,707 - INFO - run_cmd: mc admin user disable minio_admin user1
2024-04-08 11:49:27,749 - INFO - do_disable_user user1 succeed
2024-04-08 11:49:27,750 - INFO - run_cmd: mc admin user disable juice_admin user1
2024-04-08 11:49:27,794 - INFO - do_disable_user user1 succeed
2024-04-08 11:49:27,794 - INFO - run_cmd: mc admin user add minio_admin user1 minioadmin
2024-04-08 11:49:27,888 - INFO - do_add_user user1 succeed
2024-04-08 11:49:27,888 - INFO - run_cmd: mc admin user add juice_admin user1 minioadmin
2024-04-08 11:49:27,990 - INFO - do_add_user user1 succeed
2024-04-08 11:49:27,990 - INFO - run_cmd: mc alias set minio_pjzm http://localhost:9000 user1 minioadmin
2024-04-08 11:49:28,019 - INFO - do_set_alias pjzm localhost:9000 user1 minioadmin succeed
2024-04-08 11:49:28,019 - INFO - run_cmd: mc alias set juice_pjzm http://localhost:9006 user1 minioadmin
2024-04-08 11:49:28,047 - INFO - do_set_alias {'alias': 'pjzm', 'url': 'localhost:9006', 'access_key': 'user1', 'secret_key': 'minioadmin'} failed: mc: <ERROR> Unable to initialize new alias from the provided credentials. The Access Key Id you provided does not exist in our records.

F
======================================================================
FAIL: test_xxx (__main__.TestS3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".github/scripts/hypo/s3_test.py", line 76, in test_xxx
    state.set_alias(alias='pjzm', url1='localhost:9000', url2='localhost:9006', user_name=v8)
  File "/root/juicefs/.github/scripts/hypo/s3.py", line 510, in set_alias
    target=aliases,
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 681, in rule_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/s3.py", line 510, in set_alias
    target=aliases,
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 802, in precondition_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/s3.py", line 520, in set_alias
    assert self.equal(result1, result2), f'\033[31mset_alias:\nresult1 is {result1}\nresult2 is {result2}\033[0m'
AssertionError: set_alias:
result1 is True
result2 is returncode:1 output:mc: <ERROR> Unable to initialize new alias from the provided credentials. The Access Key Id you provided does not exist in our records.

root@bench-01:~/juicefs# mc admin user info juice_admin user1
AccessKey: user1
Status: disabled
PolicyName:
MemberOf:
root@bench-01:~/juicefs# mc admin user info minio_admin user1
AccessKey: user1
Status: disabled
PolicyName:
MemberOf:
root@bench-01:~/juicefs# mc alias set minio_zuvd http://localhost:9000 user1 minioadmin
mc: <ERROR> Unable to initialize new alias from the provided credentials. The Access Key Id you provided does not exist in our records.
root@bench-01:~/juicefs# mc alias set juice_zuvd http://localhost:9006 user1 minioadmin
Added `juice_zuvd` successfully.

```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhoucheng361** [comment]
the config data changed in one gateway will sync to another gateway after 5 minutes.
