### ISSUE TITLE
when the cache disk is faulty，I/O drops 0 and the services is Interrupted

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs#4782]
**What happened**:
when the cache disk is faulty，I/O drops 0 and the services is Interrupted

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1、Deploy the cluster using k8s and use redis for metadata

2、run vdbench

3、use chaosmesh inject the cache disk fault
 - name: juicefs-io-fault
      templateType: IOChaos
      ioChaos:
        action: fault
        mode: one
        selector:
          namespaces:
            - kube-system
          labelSelectors:
            app.kubernetes.io/name: juicefs-mount
          nodes:
            - chaos-k8s-001
        volumePath: /data/cache
        path: /data/cache/**/*
        errno: 5
        percent: 10

4、vdbench io drops 0 two minutes and The juicefs mount point is stuck
5、vdbench  is Interrupted ：errno: EINTR: 'Interrupted system call'

juicefs log:
A", err: <nil>, cost: 2m16.68490199s) [cached_store.go:654]
2024/04/25 08:35:02.944266 juicefs[25] <WARNING>: Upload chunks/0/9/9246_9_4194304: timeout after 1m0s (try 2) [cached_store.go:403]
2024/04/25 08:34:56.080302 juicefs[25] <WARNING>: Upload chunks/0/9/9251_2_4194304: timeout after 1m0s (try 2) [cached_store.go:403]
2024/04/25 08:36:11.558221 juicefs[16] <INFO>: mount point /jfs/pvc-3a68395e-9028-4f6a-9910-779797fc929a-ufgcxl is not active for 1m9.74760219s [mount_unix.go:172]
2024/04/25 08:36:13.119646 juicefs[16] <INFO>: watchdog: kill 25 [mount_unix.go:76]
SIGABRT: abort
PC=0x486de1 m=0 sigcode=0

goroutine 31 [syscall, 6 minutes]:
runtime.notetsleepg(0x0?, 0x0?)
        /usr/local/go/src/runtime/lock_futex.go:236 +0x29 fp=0xc0006007a0 sp=0xc000600768 pc=0x421ae9
os/signal.signal_recv()
        /usr/local/go/src/runtime/sigqueue.go:152 +0x29 fp=0xc0006007c0 sp=0xc0006007a0 pc=0x480fc9
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x13 fp=0xc0006007e0 sp=0xc0006007c0 pc=0x1f06e13
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0006007e8 sp=0xc0006007e0 pc=0x484fc1
created by os/signal.Notify.func1.1 in goroutine 1
        /usr/local/go/src/os/signal/signal.go:151 +0x1f
 

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by YunhuiChen** [comment]
[log.tar.gz](https://github.com/juicedata/juicefs/files/15109013/log.tar.gz)

**Comment by YunhuiChen** [comment]
Failed to reproduce, temporarily closed
