### ISSUE TITLE
vdbench I/O error with release-1.1

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4964]
https://github.com/juicedata/juicefs/actions/runs/9608104779

```
04:24:20.836 localhost-0: 04:24:20.836 op: read   lun: /tmp/jfs/vdb.1_2.dir/vdb_f0003.file lba:     14290944 0x00DA1000 xfer:     4096 errno: EIO: 'I/O error' 
04:24:21.338 
04:24:21.338 'data_errors=1' requested. Abort rd=rd1 after last error.
04:24:21.338 
java.lang.RuntimeException: 'data_errors=1' requested. Abort rd=rd1 after last error.
	at Vdb.common.failure(common.java:350)
	at Vdb.common.failure(common.java:297)
	at Vdb.ErrorLog.countErrorsOnMaster(ErrorLog.java:224)
	at Vdb.SlaveOnMaster.processSlave(SlaveOnMaster.java:207)
	at Vdb.SlaveOnMaster.run(SlaveOnMaster.java:42)
```

**Comment by SandyXSD** [comment]
Should be fixed by #4573 in v1.2.0.

It's not picked to v1.1.3 since it only happens under heavy random writes, and can be fixed by `juicefs gc --compact` or the new `juicefs compact` command.
