### ISSUE TITLE
Class io.juicefs.JuiceFileSystem not found

### ISSUE THREAD

**Issue by ANHDY** [juicedata/juicefs#5232]
**What happened**:
采用hive-testbench-hdp3对juicefs进行tpcds测试，但是创建数据库失败

```shell
./tpcds-setup.sh 2 jfs://myjuicefs/tmp/tpcds-generate
+ '[' X2 = X ']'
+ '[' Xjfs://myjuicefs/tmp/tpcds-generate = X ']'
+ '[' 2 -eq 1 ']'
+ hdfs dfs -mkdir -p jfs://myjuicefs/tmp/tpcds-generate
24/10/15 16:50:28 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 360 minutes that is used for deletion instead
24/10/15 16:50:28 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 360 minutes, Emptier interval = 0 minutes.
+ hdfs dfs -ls jfs://myjuicefs/tmp/tpcds-generate/2
24/10/15 16:50:29 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 360 minutes that is used for deletion instead
24/10/15 16:50:29 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 360 minutes, Emptier interval = 0 minutes.
ls: `jfs://myjuicefs/tmp/tpcds-generate/2': No such file or directory
+ '[' 1 -ne 0 ']'
+ echo 'Generating data at scale factor 2.'
Generating data at scale factor 2.
+ cd tpcds-gen
+ hadoop jar target/tpcds-gen-1.0-SNAPSHOT.jar -d jfs://myjuicefs/tmp/tpcds-generate/2/ -s 2
24/10/15 16:50:31 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 360 minutes that is used for deletion instead
24/10/15 16:50:31 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 360 minutes, Emptier interval = 0 minutes.
24/10/15 16:50:31 INFO client.AHSProxy: Connecting to Application History server at emr-master-001.novalocal/192.168.5.245:10200
24/10/15 16:50:31 INFO hdfs.DFSClient: Created token for hive: HDFS_DELEGATION_TOKEN owner=hive/emr-master-001.novalocal@BCHKDC, renewer=yarn, realUser=, issueDate=1728982231661, maxDate=1729587031661, sequenceNumber=782, masterKeyId=123 on ha-hdfs:cmss
24/10/15 16:50:31 INFO security.TokenCache: Got dt for hdfs://cmss; Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:cmss, Ident: (token for hive: HDFS_DELEGATION_TOKEN owner=hive/emr-master-001.novalocal@BCHKDC, renewer=yarn, realUser=, issueDate=1728982231661, maxDate=1729587031661, sequenceNumber=782, masterKeyId=123)
24/10/15 16:50:31 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /user/hive/.staging/job_1728615830172_0139
24/10/15 16:50:31 INFO input.FileInputFormat: Total input files to process : 1
24/10/15 16:50:31 INFO mapreduce.JobSubmitter: number of splits:2
24/10/15 16:50:31 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1728615830172_0139
24/10/15 16:50:31 INFO mapreduce.JobSubmitter: Executing with tokens: [Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:cmss, Ident: (token for hive: HDFS_DELEGATION_TOKEN owner=hive/emr-master-001.novalocal@BCHKDC, renewer=yarn, realUser=, issueDate=1728982231661, maxDate=1729587031661, sequenceNumber=782, masterKeyId=123)]
24/10/15 16:50:32 INFO conf.Configuration: found resource resource-types.xml at file:/usr/bch/3.3.0/hadoop/etc/hadoop/resource-types.xml
24/10/15 16:50:32 INFO impl.TimelineClientImpl: Timeline service address: null
24/10/15 16:50:32 INFO impl.YarnClientImpl: Submitted application application_1728615830172_0139
24/10/15 16:50:32 INFO mapreduce.Job: The url to track the job: http://emr-master-001.novalocal:8088/proxy/application_1728615830172_0139/
24/10/15 16:50:32 INFO mapreduce.Job: Running job: job_1728615830172_0139
24/10/15 16:50:38 INFO mapreduce.Job: Job job_1728615830172_0139 running in uber mode : false
24/10/15 16:50:38 INFO mapreduce.Job:  map 0% reduce 0%
24/10/15 16:50:38 INFO mapreduce.Job: Job job_1728615830172_0139 failed with state FAILED due to: Application application_1728615830172_0139 failed 2 times due to AM Container for appattempt_1728615830172_0139_000002 exited with  exitCode: 1
Failing this attempt.Diagnostics: [2024-10-15 16:50:38.409]Exception from container-launch.
Container id: container_e148_1728615830172_0139_02_000001
Exit code: 1
Shell output: main : command provided 1
main : run as user is hive
main : requested yarn user is hive
Getting exit code file...
Creating script paths...
Writing pid file...
Writing to tmp file /data1/hadoop/yarn/local/nmPrivate/application_1728615830172_0139/container_e148_1728615830172_0139_02_000001/container_e148_1728615830172_0139_02_000001.pid.tmp
Writing to cgroup task files...
Creating local dirs...
Launching container...


[2024-10-15 16:50:38.430]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
log4j:WARN No appenders could be found for logger (org.apache.hadoop.mapreduce.v2.app.MRAppMaster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.


[2024-10-15 16:50:38.431]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
log4j:WARN No appenders could be found for logger (org.apache.hadoop.mapreduce.v2.app.MRAppMaster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.


For more detailed output, check the application tracking page: http://192.168.5.245:8188/applicationhistory/app/application_1728615830172_0139 Then click on links to logs of each attempt.
. Failing the application.
24/10/15 16:50:38 INFO mapreduce.Job: Counters: 0
+ hdfs dfs -ls jfs://myjuicefs/tmp/tpcds-generate/2
24/10/15 16:50:39 INFO fs.TrashPolicyDefault: The configured checkpoint interval is 0 minutes. Using an interval of 360 minutes that is used for deletion instead
24/10/15 16:50:39 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 360 minutes, Emptier interval = 0 minutes.
ls: `jfs://myjuicefs/tmp/tpcds-generate/2': No such file or directory
+ '[' 1 -ne 0 ']'
+ echo 'Data generation failed, exiting.'
Data generation failed, exiting.
+ exit 1
```

查看yarn日志出现`Class io.juicefs.JuiceFileSystem not found`

```shell
2024-10-15 16:50:38,387 ERROR [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Error starting MRAppMaster
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class io.juicefs.JuiceFileSystem not found
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$3.call(MRAppMaster.java:554)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$3.call(MRAppMaster.java:534)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.callWithJobClassLoader(MRAppMaster.java:1802)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.createOutputCommitter(MRAppMaster.java:534)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceInit(MRAppMaster.java:311)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$6.run(MRAppMaster.java:1760)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1699)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1757)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1691)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class io.juicefs.JuiceFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2592)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3369)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3401)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:125)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3452)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3420)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:478)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.<init>(FileOutputCommitter.java:160)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.<init>(FileOutputCommitter.java:116)
	at org.apache.hadoop.mapreduce.lib.output.PathOutputCommitterFactory.createFileOutputCommitter(PathOutputCommitterFactory.java:134)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitterFactory.createOutputCommitter(FileOutputCommitterFactory.java:35)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.getOutputCommitter(FileOutputFormat.java:338)
	at org.apache.hadoop.mapreduce.lib.output.FilterOutputFormat.getOutputCommitter(FilterOutputFormat.java:67)
	at org.apache.hadoop.mapreduce.lib.output.LazyOutputFormat.getOutputCommitter(LazyOutputFormat.java:92)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$3.call(MRAppMaster.java:552)
	... 11 more
Caused by: java.lang.ClassNotFoundException: Class io.juicefs.JuiceFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2496)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2590)
	... 26 more
2024-10-15 16:50:38,388 INFO [main] org.apache.hadoop.util.ExitUtil: Exiting with status 1: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class io.juicefs.JuiceFileSystem not found
```

**What you expected to happen**:
能在juicefs中创建数据库

**How to reproduce it (as minimally and precisely as possible)**:

编译hive-testbench-hdp3，并在其目录下运行./tpcds-setup.sh 2 jfs://myjuicefs/tmp/tpcds-generate

**Anything else we need to know?**

已经配置了mapreduce.application.classpath的juicefs-hadoop-1.2.0.jar路径地址，且Hadoop和hive对juicefs的验证通过。

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by tangyoupeng** [comment]
是不是nodemanager节点上没放juicefs的jar

**Comment by ANHDY** [comment]
> 是不是nodemanager节点上没放juicefs的jar

你好，想请问一下，这个nocemanager节点指的是yarn吗？需要在yarn的路径下也放juicefs的jar吗？

**Comment by tangyoupeng** [comment]
@ANHDY 是，yarn所有节点都需要放

**Comment by ANHDY** [comment]
谢谢，解决了
