### ISSUE TITLE
Apache Kafka can not run on mouted dir by JuiceFS

### ISSUE THREAD

**Issue by microeastcowboy** [juicedata/juicefs#5444]
I have mounted one directory on local disk by juice mount.  If Kafka runs in the directory , it will report an error.
`[2024-12-26 15:20:39,556] WARN (main kafka.server.BrokerMetadataCheckpoint 70) No meta.properties file under dir /mnt/kafka01/log/meta.properties
[2024-12-26 15:27:43,965] WARN (main org.apache.kafka.common.utils.Utils 827) Failed to close meta.properties.tmp with type java.io.FileOutputStream
java.io.IOException: Input/output error
        at java.io.FileOutputStream.close0(Native Method)
        at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
        at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
        at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
        at java.io.FileOutputStream.close(FileOutputStream.java:354)
        at org.apache.kafka.common.utils.Utils.closeQuietly(Utils.java:825)
        at kafka.server.BrokerMetadataCheckpoint.liftedTree1$1(BrokerMetadataCheckpoint.scala:47)
        at kafka.server.BrokerMetadataCheckpoint.write(BrokerMetadataCheckpoint.scala:36)
        at kafka.server.KafkaServer$$anonfun$checkpointBrokerId$3.apply(KafkaServer.scala:732)
        at kafka.server.KafkaServer$$anonfun$checkpointBrokerId$3.apply(KafkaServer.scala:730)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at kafka.server.KafkaServer.checkpointBrokerId(KafkaServer.scala:730)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:268)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)
[2024-12-26 15:27:43,971] ERROR (main kafka.server.KafkaServer 159) [KafkaServer id=1006] Fatal error during KafkaServer startup. Prepare to shutdown
**java.io.SyncFailedException: sync failed**
        at java.io.FileDescriptor.sync(Native Method)
        at kafka.server.BrokerMetadataCheckpoint.liftedTree1$1(BrokerMetadataCheckpoint.scala:45)
        at kafka.server.BrokerMetadataCheckpoint.write(BrokerMetadataCheckpoint.scala:36)
        at kafka.server.KafkaServer$$anonfun$checkpointBrokerId$3.apply(KafkaServer.scala:732)
        at kafka.server.KafkaServer$$anonfun$checkpointBrokerId$3.apply(KafkaServer.scala:730)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at kafka.server.KafkaServer.checkpointBrokerId(KafkaServer.scala:730)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:268)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)`

This sync means ：Force all system buffers to synchronize with the underlying device. `
Does juiceFS  support file Sync operations?

**Comment by jiefenghuang** [comment]
Can you share your juicefs log?

**Comment by microeastcowboy** [comment]
according juicefs log , it caused by the s3 service exception. this is not a problem

> Can you share your juicefs log?
