### ISSUE TITLE
not able to use google storage due to possible parsing bug when using "juicefs format"

### ISSUE THREAD

**Issue by ghettogeets** [juicedata/juicefs#78]
Hello,

I try to make use of a google cloud storage bucket called juicefs

I'm having problems providing the right command line syntax.
From `juicefs format -h` and from looking at the source code aswell as the documentation it seems I need to provide the following options:
- bucket
- accesskey
- secretkey
- redisserver
- directoryname
- Maybe a region?

In google-language a bucket is referenced like this:
`gs://juicefs` 

Entering `--bucket gs://juicefs` results in the following runtime error:
```
 ./juicefs format --storage gs --bucket gs://juicefs --accesskey Gxxxxxxxxxxxxxxxxxx --secretkey Oxxxxxxxxxxxxxxxxxxx redis://redis-master:6379/4 test3


2021/01/15 13:24:39.231337 juicefs[3546] <INFO>: Meta address: redis://redis-master:6379/4
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/juicedata/juicesync/object.newGS(0x7fffedb1a878, 0xc, 0x7fffedb1a891, 0x13, 0x7fffedb1a8b1, 0x14, 0x2, 0x0, 0x2c, 0xc000226a50)
        /go/pkg/mod/github.com/juicedata/juicesync@v0.6.3-0.20210114082630-137546625adb/object/gs.go:145 +0x3e6
github.com/juicedata/juicesync/object.CreateStorage(0x7fffedb1a86c, 0x2, 0x7fffedb1a878, 0xc, 0x7fffedb1a891, 0x13, 0x7fffedb1a8b1, 0x14, 0x2c, 0xc000226a50, ...)
        /go/pkg/mod/github.com/juicedata/juicesync@v0.6.3-0.20210114082630-137546625adb/object/object_storage.go:123 +0x1ad
github.com/juicedata/juicefs/pkg/object.CreateStorage(0x7fffedb1a86c, 0x2, 0x7fffedb1a878, 0xc, 0x7fffedb1a891, 0x13, 0x7fffedb1a8b1, 0x14, 0xc00069f8f8, 0x45f8c7, ...)
        /go/src/github.com/juicedata/juicefs/pkg/object/interface.go:57 +0x26d
main.createStorage(0xc00069fb60, 0x1588442, 0x8, 0xc000226a20, 0x24)
        /go/src/github.com/juicedata/juicefs/cmd/format.go:55 +0xa5
main.format(0xc00011c100, 0x8, 0xe)
        /go/src/github.com/juicedata/juicefs/cmd/format.go:165 +0x8fe
github.com/urfave/cli/v2.(*Command).Run(0xc00059ad80, 0xc0000cbd80, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc0004c91e0, 0x178d400, 0xc000044080, 0xc00003c0c0, 0xc, 0xc, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /go/src/github.com/juicedata/juicefs/cmd/main.go:78 +0x99c
root@juice-user-deployment-55c7f57c98-wnx96:/home#
```
Entering `--bucket gs://juicefs.` (dot at the end) lets the command run.

So after some trial-and-error I came up with a cli-command, that seems to work.

Command:
```
./juicefs format --storage gs --bucket gs://juicefs. --accesskey Gxxxxxxxxxxxxxxxxxx --secretkey Oxxxxxxxxxxxxxxxxxxx redis://redis-master:6379/5 test3 --force

```
Output:
```
2021/01/15 13:17:27.406060 juicefs[3468] <INFO>: Meta address: redis://redis-master:6379/5
2021/01/15 13:17:27.412904 juicefs[3468] <INFO>: Data uses gs://juicefs/test3/
2021/01/15 13:17:27.543149 juicefs[3468] <INFO>: Volume is formatted as {Name:test3 UUID:31777d36-1fee-4ae1-aeec-81399dc19289 Storage:gs Bucket:gs://juicefs. AccessKey:Gxxxxxxxxxxxxxxxxxx SecretKey:removed BlockSize:4096 Compression:lz4 Partitions:0}
```

Is this the right way to use the cli?
After mounting the volume I see there's new inodes created, but nothing gets synced to the cloud.

command:
```
mkdir juice
./juicefs mount redis://redis-master:6379/5 juice
```
output:
```
2021/01/15 13:21:38.852377 juicefs[3508] <INFO>: Meta address: redis://redis-master:6379/5
2021/01/15 13:21:38.859770 juicefs[3508] <INFO>: Data use gs://juicefs/test3/
2021/01/15 13:21:38.859798 juicefs[3508] <INFO>: mount volume test3 at juice
2021/01/15 13:21:38.859817 juicefs[3508] <INFO>: Cache: /var/jfsCache capacity: 1024 MB
```

**Comment by chnliyong** [comment]
Currenty, the `gs://bucket` is not supported. The details is [here](https://github.com/juicedata/juicesync/blob/master/object/gs.go#L138).

JuiceFS currently use the vhost style bucket naming style like [s3 vhost style](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html), which is `http[s]://<bucket>.<regional-endpoint>`. If the bucket doesn't exist, JuiceFS will try to create it using the provided access key and secret key in the region parsed from the `<regional-endpoint>`

For different cloud provider, the implementation may have some difference. For Google cloud storage, the expected format is: `--storage=gs --bucket=https://<bucket>.<region>`, as the SDK of Google cloud storage doesn't need the `region` parameter, the **dot at the end** works if the bucket already exists and the access key, secret key pair has permission to GET, PUT, DELETE.

You just mount the file system and not new data has been written. After mounted, you can try to write some data to this volume such as `echo "Hello world!" > juice/hello.txt` where _juice_ is your mounted directory.

**Comment by davies** [comment]
@chnliyong What's happen if the region is empty? It's better to support `--bucket=mybucket`  and `--bucket=my://mybucket`

**Comment by chnliyong** [comment]
> @chnliyong What's happen if the region is empty? It's better to support `--bucket=mybucket` and `--bucket=my://mybucket`

If the region is empty, JuiceFS cannot determine which region to create a bucket if the bucket doesn't exist.

Yeah, we can support this shortcut format like `gs://bucket` and if the bucket doesn't exist and we can logging an error message and exit. I'll try this.

**Comment by davies** [comment]
> Yeah, we can support this shortcut format like `gs://bucket` and if the bucket doesn't exist and we can logging an error message and exit. I'll try this.

Maybe we can find the local region if the VM is inside GCP

**Comment by davies** [comment]
Fixed by 322d552ca1de4bb556b6151eca4d817da9ad4eb8
